export const navbarLinks = [
  { menu: "About Us", ref: "/about", path: "about" },
  { menu: "Services", ref: "/services", path: "services" },
  { menu: "Products", ref: "/products", path: "products" },
  { menu: "Certifications", ref: "/certifications", path: "certifications" },
  { menu: "Gallery", ref: "/gallery", path: "gallery" },
  { menu: "Contact us", ref: "/contact", path: "contact" },
];

export const footerLinks = [
  { menu: "Home", ref: "/" },
  // { menu: "People of rasims", ref: "/initiatives#founder" },
  { menu: "ROC", ref: "/roc" },

  { menu: "T&C", ref: "/termsAndConditions" },
  { menu: "Policy", ref: "/policy" },
];

export const fabricTypes = [
  {
    title: "Men",
    desc: "Wool is not just a fiber, it’s a lifestyle.",
    ref: "/products#types",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/cards/mens-wear.png",
    link: "More",
  },
  {
    title: "Women",
    desc: "Denim is a love that never fades.",
    ref: "/products#types",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/image-4.png",
    link: "More",
  },
  {
    title: "Children",
    desc: "Cotton is the fabric of our lives.",
    ref: "/products#types",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/image-10.png",
    link: "More",
  },
  {
    title: "Infants",
    desc: "Cotton is the fabric of our lives.",
    ref: "/products#types",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/infants/WhatsApp%20Image%202024-10-18%20at%2018.25.16_70ebb16f.png",
    link: "More",
  },
];

export const certification = [
  {
    title: "sedex",
    desc: "",
    ref: "/certifications#certificate",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/certification%20logo/sedex-logo.webp",
    link: "More",
  },
  // {
  //   title: "ECCC",
  //   desc: "",
  //   ref: "/certifications#certificate",
  //   img: "https://cdn.shopifyapp.shop/Rasim%20exports/certification%20logo/sa8000-logo.webp",
  //   link: "More",
  // },
  {
    title: "GOTS",
    desc: "",
    ref: "/certifications#certificate",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/certification%20logo/gots-logo.jpg",
    link: "More",
  },
  // {
  //   title: "Accordia",
  //   desc: "",
  //   ref: "/certifications#certificate",
  //   img: "https://cdn.shopifyapp.shop/Rasim%20exports/certification%20logo/accordia-logo.png",
  //   link: "More",
  // },
  {
    title: "Oek Tex",
    desc: "",
    ref: "/certifications#certificate",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/certification%20logo/tex-logo.png",
    link: "More",
  },
  {
    title: "Wrap",
    desc: "",
    ref: "/certifications#certificate",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/certification%20logo/wrap-logo.png",
    link: "More",
  },
  {
    title: "organic blend",
    desc: "",
    ref: "/certifications#certificate",
    img: "https://mywebibeeworld.b-cdn.net/Rasim%20exports/certification%20logo/organic-logo.png",
    link: "More",
  },
];

export const variousProducts = [
  {
    title: "Men",
    ref: "/products#types",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/grid%201.png",
    lists: ["Shirts", "Shorts"],
  },
  {
    title: "Women",
    ref: "/products#types",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/grid%202.png",
    lists: ["Shirts", "Skirts"],
  },
  {
    title: "Children",
    ref: "/products#types",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/grid%203.png",
    lists: ["Top", "bottom"],
  },
  {
    title: "Infants",
    ref: "/products#types",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/grid%204.png",
    lists: ["Shirts", "Shorts"],
  },
];

export const carouselImg = [
  {
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/Initiatives_Page/slide%201.jpg",
    style: "object-center",
  },

  {
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/gallery_page/gallery1.jpg",
    style: "object-center",
  },
  {
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/gallery_page/gallery3.jpg",
    style: "object-center",
  },

  {
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/gallery_page/gallery4.jpg",
    style: "object-top",
  },

  {
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/Initiatives_Page/initiativesBgHero.jpeg",
    style: "object-center",
  },
  {
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/gallery_page/gallery7.jpg",
    style: "object-center",
  },
  {
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/gallery_page/gallery8.jpg",
    style: "object-center",
  },
  {
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/gallery_page/gallery9.jpg",
    style: "object-center",
  },
  {
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/product_page/Fabric%20collections/fabric%204.jpeg",
    style: "object-center",
  },
];

export const logos = [
  {
    alt: "Hinano Life",
    src: "https://cdn.shopifyapp.shop/Rasim%20exports/logo/rasimbuyers/Ellipse%205.svg",
  },
  {
    alt: "Petrol",
    src: "https://cdn.shopifyapp.shop/Rasim%20exports/logo/rasimbuyers/Ellipse%204.svg",
  },
  {
    alt: "Pan Handle",
    src: "https://cdn.shopifyapp.shop/Rasim%20exports/logo/rasimbuyers/Ellipse%208.svg",
  },
  {
    alt: "OldTejas",
    src: "https://cdn.shopifyapp.shop/Rasim%20exports/logo/rasimbuyers/lo5.svg",
  },
  {
    alt: "Ellus",
    src: "https://cdn.shopifyapp.shop/Rasim%20exports/logo/rasimbuyers/c2.svg",
  },
  {
    alt: "ariat",
    src: "https://cdn.shopifyapp.shop/Rasim%20exports/logo/rasimbuyers/Ellipse%202.svg",
  },
  {
    alt: "Silent Theory",
    src: "https://cdn.shopifyapp.shop/Rasim%20exports/logo/rasimbuyers/c4.svg",
  },
  {
    alt: "Little Dutch",
    src: "https://cdn.shopifyapp.shop/Rasim%20exports/logo/rasimbuyers/Ellipse%203.svg",
  },
  {
    alt: "Rock&Roll",
    src: "https://cdn.shopifyapp.shop/Rasim%20exports/logo/rasimbuyers/Ellipse%201.svg",
  },
  {
    alt: "French Connection",
    src: "https://cdn.shopifyapp.shop/Rasim%20exports/logo/rasimbuyers/Ellipse%206.svg",
  },
  {
    alt: "Molo",
    src: "https://cdn.shopifyapp.shop/Rasim%20exports/logo/rasimbuyers/Ellipse%207.svg",
  },
  {
    alt: "Mormaii",
    src: "https://cdn.shopifyapp.shop/Rasim%20exports/logo/rasimbuyers/c3.svg",
  },
];

export const fabricCollections = [
  {
    category: "Fabric",
    alt: "fabric name 1",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/1.jpg",
    type: "100% COTTON Putta Dobby",
    material: "60s+2/40s x 60s / 92 x 72",
  },
  {
    category: "Fabric",
    alt: "fabric name 2",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/2.jpg",
    type: "100% Viscose 2/2 Twill",
    material: "30 sf x 30 sf /112x68",
  },
  {
    category: "Fabric",
    alt: "fabric name 3",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/3.jpg",
    type: "100% COTTON Y/D SEER SUCKER CHECK",
    material: "60s x 60s / 148x88",
  },
  {
    category: "Fabric",
    alt: "fabric name 4",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/4.jpg",
    type: "100 % Organic Cotton Y/D Stripes",
    material: "20s /10s 56 x 48",
  },
  {
    category: "Fabric",
    alt: "fabric name 5",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/5.jpg",
    type: "100% Cotton Y/D flannel Check",
    material: "2/20s x 2/20s/, 56x44",
  },
  {
    category: "Fabric",
    alt: "fabric name 6",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/6.jpg",
    type: "99 % Cotton,1 % Lurex",
    material: "60 s+ Lurex x 6o s /114/29",
  },
  {
    category: "Fabric",
    alt: "fabric name 7",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/7.jpg",
    type: "100% Viscose 2/1 Twill",
    material: "30 sf x 30 sf /112x68",
  },
  {
    category: "Fabric",
    alt: "fabric name 8",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/8.jpg",
    type: "TENSILE FABRIC",
    material: "20 s x 16 Lycra /108x56 , 3/1 drill",
  },
  {
    category: "Fabric",
    alt: "fabric name 9",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/9.jpg",
    type: "100% Viscose 2/1 Drill",
    material: "30 sf x 30 sf /112x68",
  },
  {
    category: "Fabric",
    alt: "fabric name 10",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/10.jpg",
    type: "100% Cotton Double Cloth",
    material: "20s +2/40s x 20s+2/40s/112 x 92",
  },
  {
    category: "Fabric",
    alt: "fabric name 11",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/11.jpg",
    type: "100 Cotton Heavy twill -Double side brushing",
    material: "2/10s X 2/10s/44 x 32",
  },
  {
    category: "Fabric",
    alt: "fabric name 12",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/12.jpg",
    type: "100% Cotton Y/D Grindle Fabric",
    material: "2/40s x 2/40s/62 x 58",
  },
  {
    category: "Fabric",
    alt: "fabric name 13",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/13.jpg",
    type: "97% Cotton 3% Spandex",
    material: "50 s x 50 s Lycra/ 132x 72",
  },
  {
    category: "Fabric",
    alt: "fabric name 14",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/14.jpg",
    type: "97% Cotton 3% Spandex",
    material: "50 s x 50 s Lycra/ 132x 72",
  },
  {
    category: "Fabric",
    alt: "fabric name 15",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/15.jpg",
    type: "97% Cotton 3% Spandex",
    material: "50 s x 50 s Lycra/ 132x 72",
  },
  {
    category: "Fabric",
    alt: "fabric name 16",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/16.jpg",
    type: "97% Cotton 3% Spandex",
    material: "50 s x 50 s Lycra/ 132x 72",
  },
  {
    category: "Fabric",
    alt: "fabric name 17",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/17.jpg",
    type: "100% Viscose 2/2 Twill",
    material: "40 vis x 40 vis /92x72",
  },
  {
    category: "Fabric",
    alt: "fabric name 18",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/18.jpg",
    type: "100% Viscose 2/2 Twill",
    material: "40 vis x 40 vis /92x72",
  },
  {
    category: "Fabric",
    alt: "fabric name 19",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/19.jpg",
    type: "100% Viscose 2/2 Twill",
    material: "40 vis x 40 vis /92x72",
  },
  {
    category: "Fabric",
    alt: "fabric name 20",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/20.jpg",
    type: "100% Viscose 2/2 Twill",
    material: "40 vis x 40 vis /92x72",
  },
  {
    category: "Fabric",
    alt: "fabric name 21",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/21.jpg",
    type: "100% Viscose 2/2 Twill",
    material: "30 vis x 30 vis /92x64",
  },
  {
    category: "Fabric",
    alt: "fabric name 22",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/22.jpg",
    type: "100% Viscose 2/2 Twill",
    material: "30 vis x 30 vis /92x64",
  },
  {
    category: "Fabric",
    alt: "fabric name 23",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/23.jpg",
    type: "100 % Cotton 18 Wales Corduroy",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 24",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/24.jpg",
    type: "100 % Cotton 18 Wales Corduroy Y/D Checked",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 25",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/25.jpg",
    type: "100 % Cotton 18 Wales Corduroy Y/D Checked",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 26",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/26.jpg",
    type: "100 % Cotton 18 Wales Corduroy Y/D Checked",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 27",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/27.jpg",
    type: '2" x 2" onion quilted with a 40 GSM single side PP woven',
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 28",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/28.jpg",
    type: '2" x 2" onion quilted with a 40 GSM single side PP woven',
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 29",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/29.jpg",
    type: "100 % Cotton All over EMB",
    material: "40s x 40s / 92 x 88",
  },
  {
    category: "Fabric",
    alt: "fabric name 30",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/30.jpg",
    type: "Multi flower print 100 Viscose 2/1 twill",
    material: "30sf x 30sf / 1112 x 68",
  },
  {
    category: "Fabric",
    alt: "fabric name 31",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/31.jpg",
    type: "100%  Cotton Twill Y/D Check with top side peached",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 32",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/32.jpg",
    type: "Y/D /Stripes Plain weave 100 % Cotton ",
    material: "30s SL x 30s SL",
  },
  {
    category: "Fabric",
    alt: "fabric name 33",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/33.jpg",
    type: "Y/D /Stripes Plain weave 100 % Cotton",
    material: "30s SL x 30s SL",
  },
  {
    category: "Fabric",
    alt: "fabric name 34",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/34.jpg",
    type: "Y/D /Stripes Plain weave 100 % Cotton",
    material: "20s SL x 20s SL",
  },
  {
    category: "Fabric",
    alt: "fabric name 35",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/35.jpg",
    type: "Chambray Plain weave 100 % Cotton",
    material: "20s SL x 20s SL",
  },
  {
    category: "Fabric",
    alt: "fabric name 36",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/36.jpg",
    type: "Y/D Stripes Cotton/Viscose",
    material: "30sf x 20s Twill",
  },
  {
    category: "Fabric",
    alt: "fabric name 37",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/37.jpg",
    type: "Y/D DObby 100 % Cotton",
    material: "30s x 30s",
  },
  {
    category: "Fabric",
    alt: "fabric name 38",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/38.jpg",
    type: "Y/D Dobby 100% Cotton",
    material: "2/60s  x 2/20s",
  },
  {
    category: "Fabric",
    alt: "fabric name 39",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/39.jpg",
    type: "Y/D Dobby 100% Cotton ",
    material: "1/20cc x 1/20cc",
  },
  {
    category: "Fabric",
    alt: "fabric name 40",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/40.jpg",
    type: "Y/D Checks 100 % Cotton",
    material: "2//20s x 2/20s HB twill",
  },
  {
    category: "Fabric",
    alt: "fabric name 41",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/41.jpg",
    type: "Y/D Checks 80% RCC /20% RCC",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 42",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/42.jpg",
    type: "12sf Flex x 12sf Flex Plain Rayon Flex",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 43",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/43.jpg",
    type: "Print AOP 100 % Cotton",
    material: "30s x 30s slub",
  },
  {
    category: "Fabric",
    alt: "fabric name 44",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/44.jpg",
    type: "Y/D Jacquard 100% Cotton",
    material: "2//40s x 10s",
  },
  {
    category: "Fabric",
    alt: "fabric name 45",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/45.jpg",
    type: "Y/D Jacquard 100% Cotton",
    material: "30s x 30s",
  },
  {
    category: "Fabric",
    alt: "fabric name 46",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/46.jpg",
    type: "Y/D Jacquard 100% Cotton",
    material: "2/40s + 2/16s x 20s",
  },
  {
    category: "Fabric",
    alt: "fabric name 47",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/47.jpg",
    type: "Y/D Jacquard Dobby weave 100% Cotton",
    material: "30s x30s",
  },
  {
    category: "Fabric",
    alt: "fabric name 48",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/48.jpg",
    type: "100% Linen",
    material: "All over print",
  },
  {
    category: "Fabric",
    alt: "fabric name 49",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/49.jpg",
    type: "Y/D Jacquard 100% Cotton",
    material: "2/20s x 10s",
  },
  {
    category: "Fabric",
    alt: "fabric name 50",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/50.jpg",
    type: "Y/D Jacquard 100% Cotton",
    material: "2/60s x 30s",
  },
  {
    category: "Fabric",
    alt: "fabric name 51",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/51.jpg",
    type: "Y/D Jacquard 100% Cotton ",
    material: "2/60s x 30s / 86x64",
  },
  {
    category: "Fabric",
    alt: "fabric name 52",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/52.jpg",
    type: "Y/D Jacquard 100% Cotton ",
    material: "2/60s x 30s / 86x64",
  },
  {
    category: "Fabric",
    alt: "fabric name 53",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/53.jpg",
    type: "Y/D Jacquard 100% Cotton",
    material: "2/60s x 30s",
  },
  {
    category: "Fabric",
    alt: "fabric name 54",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/54.jpg",
    type: "100 % cotton",
    material: "2/20s x 10s /44x 34 Flannel check",
  },
  {
    category: "Fabric",
    alt: "fabric name 55",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/55.jpg",
    type: "Bamboo + Viscose Plain Weave",
    material: "20 BAMBOO +10 sfX20 sfsl/58x44",
  },
  {
    category: "Fabric",
    alt: "fabric name 56",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/56.jpg",
    type: "20 BAMBOO + 2X20 x20  slub Plain Weave",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 57",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/57.jpg",
    type: "100 % linen 45 Lee x 60 Lee / 55x49",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 58",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/58.jpg",
    type: "70 % cotton 30 %linen 30s x30s +44 linen 68x44",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 59",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/59.jpg",
    type: "55 % cotton 45% linen 2/20sx44 linen/ 56x48",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 60",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/60.jpg",
    type: "51 % cotton 49% linen 30sx44 linen/ 100x52",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 61",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/61.jpg",
    type: "YD checks 100% Cotton 20sl x20sl 2/2 Twill",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 62",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/62.jpg",
    type: "YD checks 100% Cotton 30sl x30s plain",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 63",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/63.jpg",
    type: "YD 100% Cotton 20sl x20sl Plain",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 64",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/64.jpg",
    type: "YD checks Cotton Linen 20s x20s Plain check",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 65",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/65.jpg",
    type: "YD checks Linen cotton 60 lea+20ml x60 lea Plain check",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 66",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/66.jpg",
    type: "Y/D stripes Cotton linen 20 cl x 2o cl Plain stripe",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 67",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/67.jpg",
    type: "YD stripes Cotton  linen 30s x16+44 lea Plain stripe",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 68",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/68.jpg",
    type: "Solid 55% linen 45% Viscose 20 LEE SF x 20 LEE SF Plain",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 69",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/69.jpg",
    type: "YD stripes 60% Linen 40 %viscoze 11 Lee SF x 11 Lee sf Plain",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 70",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/70.jpg",
    type: "100 % cotton Coduroy 8 Wales",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 71",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/71.jpg",
    type: "100 % cotton Coduroy 14 Wales",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 72",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/72.jpg",
    type: "100% cotton Peached Twill 30s X10s /144x68",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 73",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/73.jpg",
    type: "100% cotton Peached Twill 16s X12s /108x56",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 74",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/74.jpg",
    type: "100% cotton Peached Twill 20s X20s /96x48",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 75",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/rasim%20fabric/75.jpg",
    type: "100% cotton Peached Twill 20s X30s /128x84",
    material: "",
  },
];

export const certificatePageLogos = [
  {
    alt: "Sodex",
    src: "https://cdn.shopifyapp.shop/Rasim%20exports/certification%20logo/sedex-logo.webp",
  },
  {
    alt: "Wrap",
    src: "https://cdn.shopifyapp.shop/Rasim%20exports/logo/rasimcertificates/Rectangle%2022.svg",
  },
  // {
  //   alt: "Accordia",
  //   src: "https://cdn.shopifyapp.shop/Rasim%20exports/logo/rasimcertificates/Rectangle%2027.svg",
  // },
  // {
  //   alt: "ECCC",
  //   src: "https://cdn.shopifyapp.shop/Rasim%20exports/logo/rasimcertificates/Rectangle%2021.svg",
  // },
  {
    alt: "GOTS",
    src: "https://cdn.shopifyapp.shop/Rasim%20exports/logo/rasimcertificates/Rectangle%2020.svg",
  },
  {
    alt: "OEKO TEX",
    src: "https://cdn.shopifyapp.shop/Rasim%20exports/logo/rasimcertificates/Rectangle%2029.svg",
  },
  {
    alt: "Organic Blended",
    src: "https://cdn.shopifyapp.shop/Rasim%20exports/logo/rasimcertificates/Rectangle%2024.svg",
  },
];

export const founderData = [
  {
    title: "Founder & Managing Director",
    desc: "R.VARUSAI MOHAMMED (B.E.)",
    ref: "/contact",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/founders/founder%201.jpeg",
    link: "Contact",
  },
  {
    title: "Director",
    desc: "V MOHAMED RASIM (B.E. , MFTech)",
    ref: "/contact",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/aboutUs_page/about%20page%20founder%202.jpeg",
    link: "Contact",
  },
];

export const founders = [
  {
    src: "https://cdn.shopifyapp.shop/Rasim%20exports/founders/founder%201.jpeg",
    name: "R.VARUSAI MOHAMMED (B.E.)",
    position: "Founder & Managing Director",
  },
  {
    src: "https://cdn.shopifyapp.shop/Rasim%20exports/aboutUs_page/about%20page%20founder%202.jpeg",
    name: "V MOHAMED RASIM (B.E. , MFTech)",
    position: "Director",
  },
  {
    src: "https://cdn.shopifyapp.shop/Rasim%20exports/founders/founder%203.jpeg",
    name: "Unknown Name",
    position: "Founder",
  },
  {
    src: "https://cdn.shopifyapp.shop/Rasim%20exports/founders/founder%204.jpeg",
    name: "Unknown Name",
    position: "Founder",
  },
  {
    src: "https://cdn.shopifyapp.shop/Rasim%20exports/founders/founder%205.jpeg",
    name: "Unknown Name",
    position: "Founder",
  },
  {
    src: "https://cdn.shopifyapp.shop/Rasim%20exports/founders/founder%206.jpeg",
    name: "Unknown Name",
    position: "Founder",
  },
  {
    src: "https://cdn.shopifyapp.shop/Rasim%20exports/founders/founder%207.jpeg",
    name: "Unknown Name",
    position: "Founder",
  },
  {
    src: "https://cdn.shopifyapp.shop/Rasim%20exports/founders/founder%208.jpeg",
    name: "Unknown Name",
    position: "Founder",
  },
];

export const REProcess = [
  {
    title: "Ethical Manufacturing",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/HomePage%20icons/RE-icon-1.svg",
    alt: "Manufacturing icon",
  },
  {
    title: "Quality Craftsmanship",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/HomePage%20icons/RE-icon-2.svg",
    alt: "Quality icon",
  },
  {
    title: "Buyer Centric approach",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/HomePage%20icons/RE-icon-3.svg",
    alt: "Buyer icon",
  },
  {
    title: "Global Standards",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/HomePage%20icons/RE-icon-4.svg",
    alt: "Global icon",
  },
  {
    title: "Efficient Port Access",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/HomePage%20icons/RE-icon-5.svg",
    alt: "Port icon",
  },
];

// modal ROC PDF

export const PDFFiles = [
  "ROC Return FY 20 - 21",
  "ROC Return FY 21 - 22",
  "ROC Return FY 22 - 23",
  "ROC Return FY 23 - 24",
];

export const PDFFilesList = [
  {
    name: "ROC Return FY 20 - 21",
    lists: [
      "/AR-20-21/AR-20-21-p-1.jpg",
      "/AR-20-21/AR-20-21-p-2.jpg",
      "/AR-20-21/AR-20-21-p-3.jpg",
      "/AR-20-21/AR-20-21-p-4.jpg",
      "/AR-20-21/AR-20-21-p-5.jpg",
      "/AR-20-21/AR-20-21-p-6.jpg",
      "/AR-20-21/AR-20-21-p-7.jpg",
      "/AR-20-21/AR-20-21-p-8.jpg",
      "/AR-20-21/AR-20-21-p-9.jpg",
      "/AR-20-21/AR-20-21-p-10.jpg",
      "/AR-20-21/AR-20-21-p-11.jpg",
      "/AR-20-21/AR-20-21-p-12.jpg",
      "/AR-20-21/AR-20-21-p-13.jpg",
    ],
  },
  {
    name: "ROC Return FY 21 - 22",
    lists: [
      "/AR-21-22/AR-21-22-P-1.jpg",
      "/AR-21-22/AR-21-22-P-2.jpg",
      "/AR-21-22/AR-21-22-P-3.jpg",
      "/AR-21-22/AR-21-22-P-4.jpg",
      "/AR-21-22/AR-21-22-P-5.jpg",
      "/AR-21-22/AR-21-22-P-6.jpg",
      "/AR-21-22/AR-21-22-P-7.jpg",
      "/AR-21-22/AR-21-22-P-8.jpg",
      "/AR-21-22/AR-21-22-P-9.jpg",
      "/AR-21-22/AR-21-22-P-10.jpg",
      "/AR-21-22/AR-21-22-P-11.jpg",
      "/AR-21-22/AR-21-22-P-12.jpg",
      "/AR-21-22/AR-21-22-P-13.jpg",
    ],
  },
  {
    name: "ROC Return FY 22 - 23",
    lists: [
      "/AR-22-23/AR-22-23-P-1.jpg",
      "/AR-22-23/AR-22-23-P-2.jpg",
      "/AR-22-23/AR-22-23-P-3.jpg",
      "/AR-22-23/AR-22-23-P-4.jpg",
      "/AR-22-23/AR-22-23-P-5.jpg",
      "/AR-22-23/AR-22-23-P-6.jpg",
      "/AR-22-23/AR-22-23-P-7.jpg",
      "/AR-22-23/AR-22-23-P-8.jpg",
      "/AR-22-23/AR-22-23-P-9.jpg",
      "/AR-22-23/AR-22-23-P-10.jpg",
      "/AR-22-23/AR-22-23-P-11.jpg",
      "/AR-22-23/AR-22-23-P-12.jpg",
      "/AR-22-23/AR-22-23-P-13.jpg",
    ],
  },
  {
    name: "ROC Return FY 23 - 24",
    lists: [
      "/AR-23-24/AR-23-24-P-1.jpg",
      "/AR-23-24/AR-23-24-P-2.jpg",
      "/AR-23-24/AR-23-24-P-3.jpg",
      "/AR-23-24/AR-23-24-P-4.jpg",
      "/AR-23-24/AR-23-24-P-5.jpg",
      "/AR-23-24/AR-23-24-P-6.jpg",
      "/AR-23-24/AR-23-24-P-7.jpg",
      "/AR-23-24/AR-23-24-P-8.jpg",
      "/AR-23-24/AR-23-24-P-9.jpg",
      "/AR-23-24/AR-23-24-P-10.jpg",
      "/AR-23-24/AR-23-24-P-11.jpg",
      "/AR-23-24/AR-23-24-P-12.jpg",
      "/AR-23-24/AR-23-24-P-13.jpg",
    ],
  },
];

// dress collections

export const mens = [
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-21.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-20.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-19.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-18.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-17.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-16.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-13.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-12.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-15.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-14.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-11.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-10.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-9.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-8.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-7.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-6.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-4.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-5.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-2.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-3.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-1.png",
    alt: "shirt",
  },
  //men's
  {
    category: "SHIRTS",
    material: "59% Cotton, 41% Rayon",
    type: "2/60s + 2/40sf x 30s/68 x 64 Y/D HB Twill Check",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-37.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "16s x 16s / 84 x 60 Y/D Jacquard",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-36.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "2/20s x 2/20s / 52 x 44 Y/D Dobby",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-35.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "2 / 60s + 2 / 60s / 68 x 54 Y / D Jacquard",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-34.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "99% Cotton, 1% Spandex",
    type: "40s x 40s + 40 Lycra / 100 x 96",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-33.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "55% Cotton, 45% Polyester ",
    type: "45 PC x 45 PC / 110 x 70 Y/D Stripes",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-32.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "2/40s x 2/40s Y/D Grindle",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-31.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "20s + 2/40s x 20s + 2/40s Y/D Double Cloth",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-30.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Viscose",
    type: "40 v/s x 40 v/s",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-29.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Viscose",
    type: "40 v/s x 40 v/s",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-28.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Viscose",
    type: "30 s/f x 40 s/f Twill AOP",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-27.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "50s + 50s / 132x72 Twill AOP",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-26.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "18-Wales Y/D Corduroy Checks",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-25.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "18-Wales Y/D Corduroy Checks",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-24.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "63% Cotton, 34% Poly, 3% Spandex",
    type: "60s x 97D Lycra /  120 x 68 Camo AOP",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-23.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "63% Cotton, 34% Poly, 3% Spandex",
    type: "60s x 97D Lycra /  120 x 68 Camo AOP",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-22.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "63% Cotton, 34% Poly, 3% Spandex",
    type: "60s x 97D Lycra /  120 x 68 Camo AOP",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-20.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Y/D Waffle Fabric Long Sleeve ",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-21.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Twill - Solid",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-18.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS-COMBO",
    material: "100% Viscose",
    type: "AOP",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-19.png",
    alt: "shirt-combo",
  },
  {
    category: "SHIRTS",
    material: "100% Linen",
    type: "Printed Shirt",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-16.png",
    alt: "shirt-combo",
  },
  {
    category: "SHIRTS",
    material: "100% Viscose",
    type: "Twill with AOP",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-17.png",
    alt: "shirt-combo",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Twill with AOP",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-14.png",
    alt: "shirt-combo",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: " Twill Denim",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-15.png",
    alt: "shirt-combo",
  },
  {
    category: "SHIRTS-COMBO",
    material: "55% Cotton, 45% Linen",
    type: "Short Sleeve Shirts",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-13.png",
    alt: "shirt-combo",
  },
  {
    category: "SHIRTS-COMBO",
    material: "100% Viscose",
    type: "AOP Short Sleeve",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-12.png",
    alt: "shirt-combo",
  },
  {
    category: "SHIRTS-COMBO",
    material: "97% Cotton, 3% Spandex",
    type: "Long Sleeve Shirts",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-11.png",
    alt: "shirt-combo",
  },
  {
    category: "SHIRTS-COMBO",
    material: "100% Cotton",
    type: "Y/D Jacquard Long Sleeve Shirts",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-10.png",
    alt: "shirt-combo",
  },
  {
    category: "SHIRTS-COMBO",
    material: "100% Cotton",
    type: "Y/D Grindle Fabric Long Sleeve Shirts",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-9.png",
    alt: "shirt-combo",
  },
  {
    category: "SHIRTS-COMBO",
    material: "100% Cotton",
    type: "Y/D Waffle fabric Short Sleeve Shirts",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-8.png",
    alt: "shirt-combo",
  },
  {
    category: "SHIRTS-COMBO",
    material: "100% Cotton",
    type: "Y/D Waffle Check Short Sleeve",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-7.png",
    alt: "shirt-combo",
  },
  {
    category: "SHIRTS-COMBO",
    material: "100% Cotton",
    type: "Y/D Waffle Fabric Long Sleeve Shirts",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-6.png",
    alt: "shirt-combo",
  },
  {
    category: "SHACKETS",
    material: "100% Cotton",
    type: "Heavy Weight Y/D Shackets",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-5.png",
    alt: "Shackets",
  },
  {
    category: "SHORTS",
    material: "100% Cotton",
    type: "Cargo Shorts",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-4.png",
    alt: "shorts",
  },
  {
    category: "SHORTS",
    material: "100% Cotton",
    type: "Cargo Shorts",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image.png",
    alt: "shorts",
  },
  {
    category: "SHORTS",
    material: "100% Cotton",
    type: "Cargo Shorts",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-2.png",
    alt: "shorts",
  },
  {
    category: "SHORTS",
    material: "100% Cotton",
    type: "Cargo Shorts",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-1.png",
    alt: "shorts",
  },
  {
    category: "SHORTS",
    material: "100% Cotton",
    type: "Cargo Shorts",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/men/image-3.png",
    alt: "shorts",
  },
];

export const women = [
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "5 Oz Twill Denim",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/image-20.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Zaves Chambray Shirt",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/image-21.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "3/4th Sleeve Top With Waist Tie Up",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/image-19.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Long Sleeve Denim Shirt",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/image-18.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Checked Shirt",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/WhatsApp%20Image%202024-10-20%20at%2015.12.25_a199baa0.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Long Sleeve Denim Shirt",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/image-17.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Modal",
    type: "Long Sleeves",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/image-16.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "60% Cotton, 40% Viscose",
    type: "Long Sleeves",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/image-15.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Long Sleeves",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/image-14.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Double cloth Y/D Checks",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/image-13.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Organic Cotton - Crinkle",
    type: "Embroidery Top",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/image-12.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Y/D Checks",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/image-11.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton Twill",
    type: "10.5 Oz",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/img-1.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton Twill,Denim",
    type: "5 Oz",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/img-2.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton Twill",
    type: "5 Oz",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/img-3.png",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton Twill,Denim",
    type: "5 Oz",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/img-4.png",
    alt: "shirt",
  },
  {
    category: "DRESS",
    material: "100% Cotton",
    type: "5 Oz Twill Denim Chambray Puff Sleeve Dress",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/image-10.png",
    alt: "Dress",
  },
  {
    category: "DRESS",
    material: "100% Cotton",
    type: "5 Oz Twill Denim Dress",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/image-9.png",
    alt: "Dress",
  },
  {
    category: "DRESS",
    material: "100% Cotton",
    type: " 5 Oz Twill Denim",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/image-8.png",
    alt: "Dress",
  },
  {
    category: "DRESS",
    material: "98% Cotton, 2% Spandex",
    type: "Denim Mini Dress",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/image-7.png",
    alt: "Dress",
  },
  {
    category: "DRESS",
    material: "98.5% Cotton, 1.5% Elasthane",
    type: "10 Oz Stretch Denim Women Dress",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/image-6.png",
    alt: "Dress",
  },
  {
    category: "DRESS",
    material: "100% Cotton",
    type: "Denim Long Dress",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/image-5.png",
    alt: "Dress",
  },
  {
    category: "DRESS",
    material: "100% Cotton",
    type: "5 Oz Sleeveless Twill Denim Swirt Dress",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/image-3.png",
    alt: "Dress",
  },
  {
    category: "DRESS",
    material: "100% Cotton",
    type: "5 Oz Twill Denim",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/image-4.png",
    alt: "Dress",
  },
  {
    category: "DRESS",
    material: "100% Cotton",
    type: "Y/D Satin Women's Dress",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/image-2.png",
    alt: "Dress",
  },
  {
    category: "DRESS",
    material: "100% Cotton Twill",
    type: "5 Oz",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/dress%20img-5.png",
    alt: "Dress",
  },
  {
    category: "DRESS",
    material: "98% Cotton,2% Spandex Twill",
    type: "10 OZ",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/dress%20img-6.png",
    alt: "Dress",
  },
  {
    category: "DRESS",
    material: "100% Cotton Twill",
    type: "5 Oz",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/dress%20img-7.png",
    alt: "Dress",
  },
  {
    category: "DUNGAREE",
    material: "100% Cotton",
    type: "5 Oz Denim Dungaree",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/image-1.png",
    alt: "Dungaree",
  },
  {
    category: "DUNGAREE",
    material: "100% Cotton blend",
    type: "6 Oz",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/dg%20img-8.png",
    alt: "Dungaree",
  },
  {
    category: "DUNGAREE",
    material: "100% Cotton Twill,Denim",
    type: "5 Oz",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/dg%20img-9.png",
    alt: "Dungaree",
  },
  {
    category: "SHORTS",
    material: "100% Cotton",
    type: "5 Oz Denim Chambray Shorts ",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/women/image.png",
    alt: "Shorts",
  },
];

export const kids = [
  {
    category: "BOYS SHIRTS",
    material: "100% Cotton",
    type: "3/4th Sleeve with Checks & Embroidery",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/WhatsApp%20Image%202024-10-20%20at%2015.15.43_c2f40b71.png",
    alt: "Boys Shirt",
  },
  {
    category: "BOYS SHIRTS",
    material: "60% Recycled Cotton, 40% Polyester",
    type: "Y/D Twill Checks",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2012.02.59_e92e1993.png",
    alt: "Boys Shirt",
  },
  {
    category: "BOYS SHIRTS",
    material: "100% Cotton",
    type: "YD checks",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/image-17.png",
    alt: "Boys Shirt",
  },
  {
    category: "BOYS SHIRTS",
    material: "100% Cotton",
    type: "Long Sleeve",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/image-18.png",
    alt: "Boys Shirt",
  },
  {
    category: "BOYS SHIRTS",
    material: "100% Cotton",
    type: "Dobby",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/image-15.png",
    alt: "Boys Shirt",
  },
  {
    category: "BOYS SHIRTS",
    material: "100% Cotton",
    type: "YD checks",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/image-14.png",
    alt: "Boys Shirt",
  },
  {
    category: "BOYS SHIRTS",
    material: "100% Cotton",
    type: "Y/D with Jersey",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/image-13.png",
    alt: "Boys Shirt",
  },
  {
    category: "GIRLS DRESS",
    material: "100% Viscose with AOP",
    type: "Long Sleeve Dress",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/WhatsApp%20Image%202024-10-18%20at%2018.20.54_af70f0c1.png",
    alt: "Girls Dress",
  },
  {
    category: "GIRLS DRESS",
    material: " 100% Cotton",
    type: "AOP Double Cloth Dress",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2011.59.49_73d0b95b.png",
    alt: "Girls Dress",
  },
  {
    category: "GIRLS DRESS",
    material: "50% Viscose, 50% Cotton",
    type: "Double cloth Solid Half Sleeve Dress",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2017.41.03_5fe77043.png",
    alt: "Girls Dress",
  },
  {
    category: "GIRLS DRESS",
    material: "100% Cotton",
    type: "Y/D Twill Checks",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2012.05.49_08bcfec2.png",
    alt: "Girls Dress",
  },
  {
    category: "GIRLS DRESS",
    material: "100% Cotton",
    type: "Seersucker Floral AOP Dress With Chest Smoking",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/WhatsApp%20Image%202024-10-20%20at%2016.14.02_eef54720.png",
    alt: "Girls Dress",
  },
  {
    category: "GIRLS DRESS",
    material: "100% Tencil",
    type: "Girl’s Dress",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/image-12.png",
    alt: "Girls Dress",
  },
  {
    category: "GIRLS DRESS",
    material: "100% Rayon",
    type: "Girl’s Dress",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/image-9.png",
    alt: "Girls Dress",
  },
  {
    category: "GIRLS DRESS",
    material: "100% Viscose",
    type: "AOP",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/image-10.png",
    alt: "Girls Dress",
  },
  {
    category: "SKIRTS",
    material: "100% Viscose",
    type: "100% Organic Cotton",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2011.42.29_6d85cbba.png",
    alt: "Skirts",
  },
  {
    category: "SKIRTS",
    material: "Double Panel Skirt",
    type: "Seer Sucker Y/D Checks",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/WhatsApp%20Image%202024-10-18%20at%2018.25.49_41604878.png",
    alt: "Skirts",
  },
  {
    category: "SKIRTS",
    material: "100% Cotton",
    type: "Double Panel Skirt With Waist Smoking",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2012.09.25_7202f351.png",
    alt: "Skirts",
  },
  {
    category: "SKIRTS",
    material: "100% Cotton",
    type: "Double Panel Skirt With Waist Smoking",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2010.19.28_f4a28c4a.png",
    alt: "Skirts",
  },
  {
    category: "SKIRTS",
    material: "100% Organic Cotton",
    type: "Seer Sucker Y/D Checks",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/WhatsApp%20Image%202024-10-20%20at%2015.15.44_ee6094c9.png",
    alt: "Skirts",
  },
  {
    category: "SKIRTS",
    material: "100% Cotton",
    type: "Dobby print",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/image-8.png",
    alt: "Skirts",
  },
  {
    category: "SKIRTS",
    material: "100% Viscose",
    type: "AOP",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/image-6.png",
    alt: "Skirts",
  },
  {
    category: "GIRLS BLOUSE",
    material: "50% Viscose, 50% Cotton",
    type: "Half Sleeve Blouse",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/WhatsApp%20Image%202024-10-18%20at%2018.22.18_666304d1.png",
    alt: "Skirts",
  },
  {
    category: "GIRLS BLOUSE",
    material: "100% Viscose With AOP",
    type: "Printed 3/4th Sleeve Top",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2011.44.15_9c5152f6-1.png",
    alt: "Skirts",
  },
  {
    category: "GIRLS BLOUSE",
    material: "100% Cotton",
    type: "Poplin with AOE",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/image-5.png",
    alt: "Skirts",
  },
  {
    category: "GIRLS BLOUSE",
    material: "100% Cotton",
    type: "Seer Sucker AOP",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/image-4.png",
    alt: "Skirts",
  },
  {
    category: "GIRLS SHORTS",
    material: "100% Cotton",
    type: "AOP Girls Shorts",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2012.08.06_50e56166.png",
    alt: "Shorts",
  },
  {
    category: "GIRLS SHORTS",
    material: "Linen Cotton",
    type: "Wide Fit",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/image-3.png",
    alt: "Shorts",
  },
  {
    category: "GIRLS PANT",
    material: "100% Cotton",
    type: "10 Oz Twill Denim",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2011.21.41_9697a9c3.png",
    alt: "Pants",
  },
  {
    category: "GIRLS  VEST",
    material: "100% Cotton",
    type: "Plain Weave with AOE",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/image-2.png",
    alt: "Vest",
  },
  {
    category: "GIRLS JACKET",
    material: "100% Cotton",
    type: "9 Ozs Denim",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/image-1.png",
    alt: "Jacket",
  },
  {
    category: "BOYS JACKET",
    material: "100% Cotton",
    type: "100%  Polyester Ripstop",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2012.05.04_84c4697b.png",
    alt: "Jacket",
  },
  {
    category: "BOYS JACKET",
    material: "55% Viscose, 45% Cotton",
    type: "Weft Dobby",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/kids/image.png",
    alt: "Jacket",
  },
];

export const infants = [
  {
    category: "BOYS SHIRTS",
    material: "97% Cotton, 3% Lycra",
    type: "3/4th Sleeve Solid Shirt",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/infants/image-15.png",
    alt: "Shirts",
  },
  {
    category: "BOYS SHIRTS",
    material: "55% Viscose, 45% Cotton",
    type: "Shorts sleeve",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/infants/WhatsApp%20Image%202024-10-18%20at%2018.22.55_a17a7337-1.png",
    alt: "Shirts",
  },
  {
    category: "BOYS SHIRTS",
    material: "100% Organic Cotton ",
    type: "Twill Checks Full Sleeve Shirt",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/infants/WhatsApp%20Image%202024-10-18%20at%2018.25.16_cb0c1e49.png",
    alt: "Shirts",
  },
  {
    category: "BOYS SHIRTS",
    material: "100% Organic Cotton ",
    type: "Twill Checks Full Sleeve Shirt",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/infants/WhatsApp%20Image%202024-10-18%20at%2018.25.16_70ebb16f.png",
    alt: "Shirts",
  },
  {
    category: "BOYS SHIRTS",
    material: "100%  Cotton",
    type: "Y/D Checks",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/infants/image-14.png",
    alt: "Shirts",
  },
  {
    category: "BOYS SHIRTS",
    material: "100%  Cotton",
    type: "Y/D Checks",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/infants/image-13.png",
    alt: "Shirts",
  },
  // missing
  {
    category: "GIRLS SHIRTS",
    material: "100% Tencel",
    type: "Elbow Sleeve Girls Extended Shirt",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/infants/image-12.png",
    alt: "Shirts",
  },
  {
    category: "GIRLS TOPS",
    material: "100% Cotton",
    type: "Y/D Patch Work Weave",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/infants/WhatsApp%20Image%202024-10-19%20at%2010.17.04_a9ee3910.png",
    alt: "",
  },
  {
    category: "GIRLS TOPS",
    material: "98% Cotton, 2% Lurex",
    type: "3/4th Sleeve Girls Top",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/infants/WhatsApp%20Image%202024-10-18%20at%2018.21.41_4de5ed7f.png",
    alt: "Tops",
  },
  {
    category: "GIRLS TOPS",
    material: "100% Cotton",
    type: "Seer Sucker With Floral AOP",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/infants/WhatsApp%20Image%202024-10-20%20at%2015.15.43_a94f3d4c.png",
    alt: "Tops",
  },
  {
    category: "GIRLS TOPS",
    material: "100% Cotton",
    type: "Butta Dobby",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/infants/image-12.png",
    alt: "Tops",
  },
  {
    category: "GIRLS TOPS",
    material: "100% Cotton",
    type: "Slub with AOP",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/infants/image-10.png",
    alt: "Tops",
  },
  {
    category: "GIRLS TOPS",
    material: "100% Viscose",
    type: "AOP",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/infants/image-11.png",
    alt: "Tops",
  },
  {
    category: "GIRLS TOPS",
    material: "100% Cotton",
    type: "Seer Sucker Y/D Check",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/infants/image-8.png",
    alt: "Tops",
  },
  {
    category: "GIRLS TOPS",
    material: "100% Cotton",
    type: "Top",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/infants/image-9.png",
    alt: "Tops",
  },
  {
    category: "GIRLS TOPS",
    material: "100% Viscose",
    type: "Solid",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/infants/image-6.png",
    alt: "Tops",
  },
  {
    category: "GIRLS TOPS",
    material: "100% Cotton",
    type: "Dobby",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/infants/image-7.png",
    alt: "Tops",
  },
  {
    category: "GIRLS DRESS",
    material: "100% Cotton",
    type: "Seer Sucker Infants Dress",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/infants/WhatsApp%20Image%202024-10-19%20at%2011.41.50_c963a401.png",
    alt: "Dress",
  },
  {
    category: "GIRLS DRESS",
    material: "100% Cotton",
    type: "Slub with AOP",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/infants/image-5.png",
    alt: "Dress",
  },
  {
    category: "GIRLS DRESS",
    material: "100% Cotton",
    type: "Y/D Checks",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/infants/image-3.png",
    alt: "Dress",
  },
  {
    category: "GIRLS DRESS",
    material: "100% Cotton",
    type: "Long Sleeves",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/infants/image-4.png",
    alt: "Dress",
  },
  {
    category: "JUMPSUIT",
    material: "100% Cotton",
    type: "Girl’s Jumpsuit 5 Oz Twill Denim Chambray Puff Sleeve Dress",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/infants/WhatsApp%20Image%202024-10-18%20at%2018.23.18_9f5f5565.png",
    alt: "Jumpsuit",
  },
  {
    category: "JUMPSUIT",
    material: "97% Cotton, 3% Lycra ",
    type: "Twill Lycra",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/infants/image-16.png",
    alt: "Jumpsuit",
  },
  {
    category: "GIRLS PANT",
    material: "100% Viscose",
    type: "AOP Full Length Pants With Waist Tie-up",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/infants/WhatsApp%20Image%202024-10-19%20at%2017.07.43_72eef9c2.png",
    alt: "Pants",
  },
  {
    category: "GIRLS SHORTS",
    material: "100% Cotton",
    type: "Slub with AOP",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/infants/image-1.png",
    alt: "Shorts",
  },
  {
    category: "GIRLS SHORTS",
    material: "100% Cotton",
    type: "Dobby Print",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/infants/image-2.png",
    alt: "Shorts",
  },
  {
    category: "BOYS SHORTS",
    material: "100% Organic Cotton",
    type: "Baby boy Shorts",
    img: "https://cdn.shopifyapp.shop/Rasim%20exports/dress%20collections/infants/image.png",
    alt: "Shorts",
  },
];
