export const navbarLinks = [
  { menu: "About Us", ref: "/about", path: "about" },
  { menu: "Services", ref: "/services", path: "services" },
  { menu: "Products", ref: "/products", path: "products" },
  { menu: "Certifications", ref: "/certifications", path: "certifications" },
  { menu: "Gallery", ref: "/gallery", path: "gallery" },
  { menu: "Contact us", ref: "/contact", path: "contact" },
];

export const footerLinks = [
  { menu: "Home", ref: "/" },
  // { menu: "People of rasims", ref: "/initiatives#founder" },
  { menu: "ROC", ref: "/roc" },

  { menu: "T&C", ref: "/termsAndConditions" },
  { menu: "Policy", ref: "/policy" },
];

export const fabricTypes = [
  {
    title: "Men",
    desc: "Wool is not just a fiber, it’s a lifestyle.",
    ref: "/products#types",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/cards/mens-wear.png?updatedAt=1729668433466",
    link: "More",
  },
  {
    title: "Women",
    desc: "Denim is a love that never fades.",
    ref: "/products#types",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-4.png?updatedAt=1729851394578",
    link: "More",
  },
  {
    title: "Children",
    desc: "Cotton is the fabric of our lives.",
    ref: "/products#types",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image-10.png?updatedAt=1729851433396",
    link: "More",
  },
  {
    title: "Infants",
    desc: "Cotton is the fabric of our lives.",
    ref: "/products#types",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/WhatsApp%20Image%202024-10-18%20at%2018.25.16_70ebb16f.png?updatedAt=1729851486653",
    link: "More",
  },
];

export const certification = [
  {
    title: "sedex",
    desc: "",
    ref: "/certifications#certificate",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/certification%20logo/sedex-logo.webp?updatedAt=1729674199654",
    link: "More",
  },
  {
    title: "ECCC",
    desc: "",
    ref: "/certifications#certificate",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/certification%20logo/sa8000-logo.webp?updatedAt=1729675027551",
    link: "More",
  },
  {
    title: "GOTS",
    desc: "",
    ref: "/certifications#certificate",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/certification%20logo/gots-logo.jpg?updatedAt=1729675198071",
    link: "More",
  },
  {
    title: "Accordia",
    desc: "",
    ref: "/certifications#certificate",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/certification_page/logos/logo%203.png?updatedAt=1728093506587",
    link: "More",
  },
  {
    title: "Oek Tex",
    desc: "",
    ref: "/certifications#certificate",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/certification%20logo/tex-logo.png?updatedAt=1729842583325",
    link: "More",
  },
  {
    title: "Wrap",
    desc: "",
    ref: "/certifications#certificate",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/certification%20logo/wrap-logo.png?updatedAt=1729842584266",
    link: "More",
  },
  {
    title: "organic blend",
    desc: "",
    ref: "/certifications#certificate",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/certification_page/logos/logo%207.png?updatedAt=1728093507060",
    link: "More",
  },
];

export const variousProducts = [
  {
    title: "Men",
    ref: "/products#types",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/grid%201.png?updatedAt=1729863471989",
    lists: ["Shirts", "Shorts"],
  },
  {
    title: "Women",
    ref: "/products#types",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/grid%202.png?updatedAt=1729863471993",
    lists: ["Shirts", "Skirts"],
  },
  {
    title: "Children",
    ref: "/products#types",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/grid%203.png?updatedAt=1729863471834",
    lists: ["Top", "bottom"],
  },
  {
    title: "Infants",
    ref: "/products#types",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/grid%204.png?updatedAt=1729863471800",
    lists: ["Shirts", "Shorts"],
  },
];

export const carouselImg = [
  {
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/Initiatives_Page/slide%201.jpg?updatedAt=1729760883662",
    style: "object-center",
  },


  {
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/gallery_page/gallery2.jpg?updatedAt=1729846570038",
    style: "object-center",
  },
  {
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/gallery_page/gallery3.jpg?updatedAt=1729846547773",
    style: "object-center",
  },

  {
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/gallery_page/gallery4.jpg?updatedAt=1729846545957",
    style: "object-top",
  },


  {
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/Initiatives_Page/initiativesBgHero.jpeg?updatedAt=1728273455068",
    style: "object-center",
  },
  {
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/gallery_page/gallery7.jpg?updatedAt=1729846555365",
    style: "object-center",
  },
  {
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/gallery_page/gallery8.jpg?updatedAt=1729846548361",
    style: "object-center",
  },
  {
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/gallery_page/gallery9.jpg?updatedAt=1729846556710",
    style: "object-center",
  },
  {
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/product_page/Fabric%20collections/fabric%204.jpeg?updatedAt=1728093008011",
    style: "object-center",
  },
  // {
  //   img: "https://ik.imagekit.io/webibee/Rasim-Exports/gallery_page/gallery10.jpg?updatedAt=1729846543499",
  //   style: "object-bottom",
  // },
  // {
  //   img: "https://ik.imagekit.io/webibee/Rasim-Exports/gallery_page/gallery1.jpg?updatedAt=1729846570403",
  //   style: "object-center",
  // },
];

export const logos = [
  {
    alt: "Hinano Life",
    src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimbuyers/Ellipse%205.svg",
  },
  {
    alt: "Petrol",
    src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimbuyers/Ellipse%204.svg",
  },
  {
    alt: "Pan Handle",
    src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimbuyers/Ellipse%208.svg",
  },
  {
    alt: "OldTejas",
    src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimbuyers/lo5.svg",
  },
  {
    alt: "Ellus",
    src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimbuyers/c2.svg",
  },
  {
    alt: "ariat",
    src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimbuyers/Ellipse%202.svg",
  },
  {
    alt: "Silent Theory",
    src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimbuyers/c4.svg",
  },
  {
    alt: "Little Dutch",
    src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimbuyers/Ellipse%203.svg",
  },
  {
    alt: "Rock&Roll",
    src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimbuyers/Ellipse%201.svg",
  },
  {
    alt: "French Connection",
    src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimbuyers/Ellipse%206.svg",
  },
  {
    alt: "Molo",
    src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimbuyers/Ellipse%207.svg",
  },
  {
    alt: "Mormaii",
    src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimbuyers/c3.svg",
  },
];

export const fabricCollections = [
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 1",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/1.jpg?tr:q-5",
    type: "100% COTTON Putta Dobby",
    material: "60s+2/40s x 60s / 92 x 72",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 2",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/2.jpg?tr:q-5",
    type: "100% Viscose 2/2 Twill",
    material: "30 sf x 30 sf /112x68",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 3",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/3.jpg?tr:q-5",
    type: "100% COTTON Y/D SEER SUCKER CHECK",
    material: "60s x 60s / 148x88",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 4",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/4.jpg?tr:q-5",
    type: "100 % Organic Cotton Y/D Stripes",
    material: "20s /10s 56 x 48",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 5",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/5.jpg?tr:q-5",
    type: "100% Cotton Y/D flannel Check",
    material: "2/20s x 2/20s/, 56x44",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 6",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/6.jpg?tr:q-5",
    type: "99 % Cotton,1 % Lurex",
    material: "60 s+ Lurex x 6o s /114/29",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 7",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/7.jpg?tr:q-5",
    type: "100% Viscose 2/1 Twill",
    material: "30 sf x 30 sf /112x68",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 8",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/8.jpg?tr:q-5",
    type: "TENSILE FABRIC",
    material: "20 s x 16 Lycra /108x56 , 3/1 drill",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 9",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/9.jpg?tr:q-5",
    type: "100% Viscose 2/1 Drill",
    material: "30 sf x 30 sf /112x68",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 10",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/10.jpg?tr:q-5",
    type: "100% Cotton Double Cloth",
    material: "20s +2/40s x 20s+2/40s/112 x 92",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 11",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/11.jpg?tr:q-5",
    type: "100 Cotton Heavy twill -Double side brushing",
    material: "2/10s X 2/10s/44 x 32",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 12",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/12.jpg?tr:q-5",
    type: "100% Cotton Y/D Grindle Fabric",
    material: "2/40s x 2/40s/62 x 58",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 13",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/13.jpg?tr:q-5",
    type: "97% Cotton 3% Spandex",
    material: "50 s x 50 s Lycra/ 132x 72",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 14",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/14.jpg?tr:q-5",
    type: "97% Cotton 3% Spandex",
    material: "50 s x 50 s Lycra/ 132x 72",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 15",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/15.jpg?tr:q-5",
    type: "97% Cotton 3% Spandex",
    material: "50 s x 50 s Lycra/ 132x 72",

  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 16",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/16.jpg?tr:q-5",
    type: "97% Cotton 3% Spandex",
    material: "50 s x 50 s Lycra/ 132x 72",

  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 17",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/17.jpg?tr:q-5",
    type: "100% Viscose 2/2 Twill",
    material: "40 vis x 40 vis /92x72",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 18",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/18.jpg?tr:q-5",
    type: "100% Viscose 2/2 Twill",
    material: "40 vis x 40 vis /92x72",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 19",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/19.jpg?tr:q-5",
    type: "100% Viscose 2/2 Twill",
    material: "40 vis x 40 vis /92x72",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 20",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/20.jpg?tr:q-5",
    type: "100% Viscose 2/2 Twill",
    material: "40 vis x 40 vis /92x72",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 21",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/21.jpg?tr:q-5",
    type: "100% Viscose 2/2 Twill",
    material: "30 vis x 30 vis /92x64",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 22",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/22.jpg?tr:q-5",
    type: "100% Viscose 2/2 Twill",
    material: "30 vis x 30 vis /92x64",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 23",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/23.jpg?tr:q-5",
    type: "100 % Cotton 18 Wales Corduroy",
    material: "",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 24",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/24.jpg?tr:q-5",
    type: "100 % Cotton 18 Wales Corduroy Y/D Checked",
    material: "",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 25",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/25.jpg?tr:q-5",
    type: "100 % Cotton 18 Wales Corduroy Y/D Checked",
    material: "",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 26",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/26.jpg?tr:q-5",
    type: "100 % Cotton 18 Wales Corduroy Y/D Checked",
    material: "",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 27",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/27.jpg?tr:q-5",
    type: '2" x 2" onion quilted with a 40 GSM single side PP woven',
    material: "",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 28",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/28.jpg?tr:q-5",
    type: '2" x 2" onion quilted with a 40 GSM single side PP woven',
    material: "",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 29",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/29.jpg?tr:q-5",
    type: "100 % Cotton All over EMB",
    material: "40s x 40s / 92 x 88",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 30",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/30.jpg?tr:q-5",
    type: "Multi flower print 100 Viscose 2/1 twill",
    material: "30sf x 30sf / 1112 x 68",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 31",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/31.jpg?tr:q-5",
    type: "100%  Cotton Twill Y/D Check with top side peached",
    material: "",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 32",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/32.jpg?tr:q-5",
    type: "Y/D /Stripes Plain weave 100 % Cotton ",
    material: "30s SL x 30s SL",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 33",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/33.jpg?tr:q-5",
    type: "Y/D /Stripes Plain weave 100 % Cotton",
    material: "30s SL x 30s SL",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 34",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/34.jpg?tr:q-5",
    type: "Y/D /Stripes Plain weave 100 % Cotton",
    material: "20s SL x 20s SL",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 35",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/35.jpg?tr:q-5",
    type: "Chambray Plain weave 100 % Cotton",
    material: "20s SL x 20s SL",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 36",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/36.jpg?tr:q-5",
    type: "Y/D Stripes Cotton/Viscose",
    material: "30sf x 20s Twill",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 37",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/37.jpg?tr:q-5",
    type: "Y/D DObby 100 % Cotton",
    material: "30s x 30s",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 38",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/38.jpg?tr:q-5",
    type: "Y/D Dobby 100% Cotton",
    material: "2/60s  x 2/20s",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 39",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/39.jpg?tr:q-5",
    type: "Y/D Dobby 100% Cotton ",
    material: "1/20cc x 1/20cc",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 40",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/40.jpg?tr:q-5",
    type: "Y/D Checks 100 % Cotton",
    material: "2//20s x 2/20s HB twill",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 41",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/41.jpg?tr:q-5",
    type: "Y/D Checks 80% RCC /20% RCC",
    material: "",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 42",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/42.jpg?tr:q-5",
    type: "12sf Flex x 12sf Flex Plain Rayon Flex",
    material: "",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 43",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/43.jpg?tr:q-5",
    type: "Print AOP 100 % Cotton",
    material: "30s x 30s slub",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 44",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/44.jpg?tr:q-5",
    type: "Y/D Jacquard 100% Cotton",
    material: "2//40s x 10s",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 45",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/45.jpg?tr:q-5",
    type: "Y/D Jacquard 100% Cotton",
    material: "30s x 30s",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 46",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/46.jpg?tr:q-5",
    type: "Y/D Jacquard 100% Cotton",
    material: "2/40s + 2/16s x 20s",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 47",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/47.jpg?tr:q-5",
    type: "Y/D Jacquard Dobby weave 100% Cotton",
    material: "30s x30s",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 48",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/48.jpg?tr:q-5",
    type: "100% Linen",
    material: "All over print",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 49",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/49.jpg?tr:q-5",
    type: "Y/D Jacquard 100% Cotton",
    material: "2/20s x 10s",
  },
  {
    category: "Fabric?tr:q-15",
    alt: "fabric name 50",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/50.jpg?tr:q-5",
    type: "Y/D Jacquard 100% Cotton",
    material: "2/60s x 30s",
  },
  {
    category: "Fabric",
    alt: "fabric name 51",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/51.jpg?tr:q-5",
    type: "Y/D Jacquard 100% Cotton ",
    material: "2/60s x 30s / 86x64",
  },
  {
    category: "Fabric",
    alt: "fabric name 52",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/52.jpg?tr:q-5",
    type: "Y/D Jacquard 100% Cotton ",
    material: "2/60s x 30s / 86x64",
  },
  {
    category: "Fabric",
    alt: "fabric name 53",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/53.jpg?tr:q-5",
    type: "Y/D Jacquard 100% Cotton",
    material: "2/60s x 30s",
  },
  {
    category: "Fabric",
    alt: "fabric name 54",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/54.jpg?tr:q-5",
    type: "100 % cotton",
    material: "2/20s x 10s /44x 34 Flannel check",
  },
  {
    category: "Fabric",
    alt: "fabric name 55",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/55.jpg?tr:q-5",
    type: "Bamboo + Viscose Plain Weave",
    material: "20 BAMBOO +10 sfX20 sfsl/58x44",
  },
  {
    category: "Fabric",
    alt: "fabric name 56",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/56.jpg?tr:q-5",
    type: "20 BAMBOO + 2X20 x20  slub Plain Weave",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 57",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/57.jpg?tr:q-5",
    type: "100 % linen 45 Lee x 60 Lee / 55x49",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 58",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/58.jpg?tr:q-5",
    type: "70 % cotton 30 %linen 30s x30s +44 linen 68x44",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 59",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/59.jpg?tr:q-5",
    type: "55 % cotton 45% linen 2/20sx44 linen/ 56x48",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 60",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/60.jpg?tr:q-5",
    type: "51 % cotton 49% linen 30sx44 linen/ 100x52",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 61",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/61.jpg?tr:q-5",
    type: "YD checks 100% Cotton 20sl x20sl 2/2 Twill",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 62",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/62.jpg?tr:q-5",
    type: "YD checks 100% Cotton 30sl x30s plain",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 63",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/63.jpg?tr:q-5",
    type: "YD 100% Cotton 20sl x20sl Plain",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 64",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/64.jpg?tr:q-5",
    type: "YD checks Cotton Linen 20s x20s Plain check",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 65",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/65.jpg?tr:q-5",
    type: "YD checks Linen cotton 60 lea+20ml x60 lea Plain check",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 66",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/66.jpg?tr:q-5",
    type: "Y/D stripes Cotton linen 20 cl x 2o cl Plain stripe",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 67",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/67.jpg?tr:q-5",
    type: "YD stripes Cotton  linen 30s x16+44 lea Plain stripe",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 68",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/68.jpg?tr:q-5",
    type: "Solid 55% linen 45% Viscose 20 LEE SF x 20 LEE SF Plain",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 69",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/69.jpg?tr:q-5",
    type: "YD stripes 60% Linen 40 %viscoze 11 Lee SF x 11 Lee sf Plain",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 70",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/70.jpg?tr:q-5",
    type: "100 % cotton Coduroy 8 Wales",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 71",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/71.jpg?tr:q-5",
    type: "100 % cotton Coduroy 14 Wales",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 72",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/72.jpg?tr:q-5",
    type: "100% cotton Peached Twill 30s X10s /144x68",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 73",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/73.jpg?tr:q-5",
    type: "100% cotton Peached Twill 16s X12s /108x56",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 74",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/74.jpg?tr:q-5",
    type: "100% cotton Peached Twill 20s X20s /96x48",
    material: "",
  },
  {
    category: "Fabric",
    alt: "fabric name 75",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/rasim%20fabric/75.jpg?tr:q-5",
    type: "100% cotton Peached Twill 20s X30s /128x84",
    material: "",
  },

  // {
  //   category: "Fabric",
  //   alt: "fabric name",
  //   img: "https://ik.imagekit.io/webibee/Rasim-Exports/product_page/Fabric%20collections/fabric%201.jpeg?updatedAt=1728093008059",
  //   type: "100% Cotton Yarn dyed Jacquard",
  //   material: "",
  // },
  // {
  //   alt: "fabric name",
  //   img: "https://ik.imagekit.io/webibee/Rasim-Exports/product_page/Fabric%20collections/fabric%202.jpeg?updatedAt=1728092998646",
  //   type: "98% Cotton 2% Lurex Plain Weave",
  //   material: "",
  // },
  // {
  //   alt: "fabric name",
  //   img: "https://ik.imagekit.io/webibee/Rasim-Exports/product_page/Fabric%20collections/fabric%203.jpeg?updatedAt=1728093006684",
  //   type: "55% Cotton 45% Linen",
  //   material: "",
  // },
  // {
  //   alt: "fabric name",
  //   img: "https://ik.imagekit.io/webibee/Rasim-Exports/product_page/Fabric%20collections/fabric%204.jpeg?updatedAt=1728093008011",
  //   type: "98% Cotton 2% Lycra",
  //   material: "",
  // },
  // {
  //   alt: "fabric name",
  //   img: "https://ik.imagekit.io/webibee/Rasim-Exports/product_page/Fabric%20collections/fabric%205.jpeg?updatedAt=1728093004809",
  //   type: "10 Oz Denim 98% Cotton 2% Elasthane Twil Denim",
  //   material: "",
  // },
  // {
  //   alt: "fabric name",
  //   img: "https://ik.imagekit.io/webibee/Rasim-Exports/product_page/Fabric%20collections/fabric%206.jpeg?updatedAt=1728093006041",
  //   type: "5.5 Oz Twill Denim 100% Cotton",
  //   material: "",
  // },
];

export const certificatePageLogos = [
  {
    alt: "Sodex",
    src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimcertificates/Rectangle%2028.svg",
  },
  {
    alt: "Wrap",
    src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimcertificates/Rectangle%2022.svg",
  },
  {
    alt: "Accordia",
    src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimcertificates/Rectangle%2027.svg",
  },
  {
    alt: "ECCC",
    src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimcertificates/Rectangle%2021.svg",
  },
  {
    alt: "GOTS",
    src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimcertificates/Rectangle%2020.svg",
  },
  {
    alt: "OEKO TEX",
    src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimcertificates/Rectangle%2029.svg",
  },
  {
    alt: "Organic Blended",
    src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimcertificates/Rectangle%2024.svg",
  },
];

export const founderData = [
  {
    title: "Founder & Managing Director",
    desc: "R.VARUSAI MOHAMMED (B.E.)",
    ref: "/contact",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/founders/founder%201.jpeg?updatedAt=1729679727380",
    link: "Contact",
  },
  {
    title: "Director",
    desc: "V MOHAMED RASIM (B.E. , MFTech)",
    ref: "/contact",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/aboutUs_page/about%20page%20founder%202.jpeg?updatedAt=1728299397544",
    link: "Contact",
  },
];

export const founders = [
  {
    src: "https://ik.imagekit.io/webibee/Rasim-Exports/founders/founder%201.jpeg?updatedAt=1728273260885",
    name: "R.VARUSAI MOHAMMED (B.E.)",
    position: "Founder & Managing Director",
  },
  {
    src: "https://ik.imagekit.io/webibee/Rasim-Exports/aboutUs_page/about%20page%20founder%202.jpeg?updatedAt=1728299397544",
    name: "V MOHAMED RASIM (B.E. , MFTech)",
    position: "Director",
  },
  {
    src: "https://ik.imagekit.io/webibee/Rasim-Exports/founders/founder%203.jpeg?updatedAt=1728273259296",
    name: "Unknown Name",
    position: "Founder",
  },
  {
    src: "https://ik.imagekit.io/webibee/Rasim-Exports/founders/founder%204.jpeg?updatedAt=1728273260405",
    name: "Unknown Name",
    position: "Founder",
  },
  {
    src: "https://ik.imagekit.io/webibee/Rasim-Exports/founders/founder%205.jpeg?updatedAt=1728273258515",
    name: "Unknown Name",
    position: "Founder",
  },
  {
    src: "https://ik.imagekit.io/webibee/Rasim-Exports/founders/founder%206.jpeg?updatedAt=1728273260483",
    name: "Unknown Name",
    position: "Founder",
  },
  {
    src: "https://ik.imagekit.io/webibee/Rasim-Exports/founders/founder%207.jpeg?updatedAt=1728273258933",
    name: "Unknown Name",
    position: "Founder",
  },
  {
    src: "https://ik.imagekit.io/webibee/Rasim-Exports/founders/founder%208.jpeg?updatedAt=1728273259787",
    name: "Unknown Name",
    position: "Founder",
  },
];

export const REProcess = [
  {
    title: "Ethical Manufacturing",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/HomePage%20icons/RE-icon-1.svg",
    alt: "Manufacturing icon",
  },
  {
    title: "Quality Craftsmanship",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/HomePage%20icons/RE-icon-2.svg",
    alt: "Quality icon",
  },
  {
    title: "Buyer Centric approach",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/HomePage%20icons/RE-icon-3.svg",
    alt: "Buyer icon",
  },
  {
    title: "Global Standards",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/HomePage%20icons/RE-icon-4.svg",
    alt: "Global icon",
  },
  {
    title: "Efficient Port Access",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/HomePage%20icons/RE-icon-5.svg",
    alt: "Port icon",
  },
];

// dress collections

export const mens = [
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-21.png?updatedAt=1729851357043?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-20.png?updatedAt=1729851356579?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-19.png?updatedAt=1729851354220?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-18.png?updatedAt=1729851346898?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-17.png?updatedAt=1729851346716?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-16.png?updatedAt=1729851347025?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-13.png?updatedAt=1729851345741?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-12.png?updatedAt=1729851344787?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-15.png?updatedAt=1729851347100?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-14.png?updatedAt=1729851347065?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-11.png?updatedAt=1729851346699?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-10.png?updatedAt=1729851347102?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-9.png?updatedAt=1729851359982?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-8.png?updatedAt=1729851358755?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-7.png?updatedAt=1729851357970?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-6.png?updatedAt=1729851358474?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-4.png?updatedAt=1729851358675?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-5.png?updatedAt=1729851358033?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-2.png?updatedAt=1729851354293?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-3.png?updatedAt=1729851355916?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image.png?updatedAt=1729851360022?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Hawaiian Print Short Sleeves",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-1.png?updatedAt=1729851345277?tr:q-15",
    alt: "shirt",
  },
  //men's
  {
    category: "SHIRTS",
    material: "59% Cotton, 41% Rayon",
    type: "2/60s + 2/40sf x 30s/68 x 64 Y/D HB Twill Check",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-37.png?updatedAt=1729851317284?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "16s x 16s / 84 x 60 Y/D Jacquard",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-36.png?updatedAt=1729851302382?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "2/20s x 2/20s / 52 x 44 Y/D Dobby",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-35.png?updatedAt=1729851301469?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "2 / 60s + 2 / 60s / 68 x 54 Y / D Jacquard",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-34.png?updatedAt=1729851301979?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "99% Cotton, 1% Spandex",
    type: "40s x 40s + 40 Lycra / 100 x 96",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-33.png?updatedAt=1729851302108?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "55% Cotton, 45% Polyester ",
    type: "45 PC x 45 PC / 110 x 70 Y/D Stripes",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-32.png?updatedAt=1729851292008?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "2/40s x 2/40s Y/D Grindle",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-31.png?updatedAt=1729851290416?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "20s + 2/40s x 20s + 2/40s Y/D Double Cloth",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-30.png?updatedAt=1729851292494?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Viscose",
    type: "40 v/s x 40 v/s",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-29.png?updatedAt=1729851292946?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Viscose",
    type: "40 v/s x 40 v/s",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-28.png?updatedAt=1729851292376?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Viscose",
    type: "30 s/f x 40 s/f Twill AOP",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-27.png?updatedAt=1729851290822 ?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "50s + 50s / 132x72 Twill AOP",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-26.png?updatedAt=1729851288250?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "18-Wales Y/D Corduroy Checks",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-25.png?updatedAt=1729851285478?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "18-Wales Y/D Corduroy Checks",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-24.png?updatedAt=1729851280003?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "63% Cotton, 34% Poly, 3% Spandex",
    type: "60s x 97D Lycra /  120 x 68 Camo AOP",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-23.png?updatedAt=1729851283486?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "63% Cotton, 34% Poly, 3% Spandex",
    type: "60s x 97D Lycra /  120 x 68 Camo AOP",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-22.png?updatedAt=1729851278592?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "63% Cotton, 34% Poly, 3% Spandex",
    type: "60s x 97D Lycra /  120 x 68 Camo AOP",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-20.png?updatedAt=1729851276258?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Y/D Waffle Fabric Long Sleeve ",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-21.png?updatedAt=1729851277393?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Twill - Solid",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-18.png?updatedAt=1729851272159?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS-COMBO",
    material: "100% Viscose",
    type: "AOP",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-19.png?updatedAt=1729851275313?tr:q-15",
    alt: "shirt-combo",
  },
  {
    category: "SHIRTS",
    material: "100% Linen",
    type: "Printed Shirt",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-16.png?updatedAt=1729851273198?tr:q-15",
    alt: "shirt-combo",
  },
  {
    category: "SHIRTS",
    material: "100% Viscose",
    type: "Twill with AOP",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-17.png?updatedAt=1729851274093?tr:q-15",
    alt: "shirt-combo",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Twill with AOP",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-14.png?updatedAt=1729851274383?tr:q-15",
    alt: "shirt-combo",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: " Twill Denim",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-15.png?updatedAt=1729851272555?tr:q-15",
    alt: "shirt-combo",
  },
  {
    category: "SHIRTS-COMBO",
    material: "55% Cotton, 45% Linen",
    type: "Short Sleeve Shirts",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-13.png?updatedAt=1729851269449?tr:q-15",
    alt: "shirt-combo",
  },
  {
    category: "SHIRTS-COMBO",
    material: "100% Viscose",
    type: "AOP Short Sleeve",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-12.png?updatedAt=1729851274020?tr:q-15",
    alt: "shirt-combo",
  },
  {
    category: "SHIRTS-COMBO",
    material: "97% Cotton, 3% Spandex",
    type: "Long Sleeve Shirts",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-11.png?updatedAt=1729851271445?tr:q-15",
    alt: "shirt-combo",
  },
  {
    category: "SHIRTS-COMBO",
    material: "100% Cotton",
    type: "Y/D Jacquard Long Sleeve Shirts",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-10.png?updatedAt=1729851273555?tr:q-15",
    alt: "shirt-combo",
  },
  {
    category: "SHIRTS-COMBO",
    material: "100% Cotton",
    type: "Y/D Grindle Fabric Long Sleeve Shirts",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-9.png?updatedAt=1729851316452?tr:q-15",
    alt: "shirt-combo",
  },
  {
    category: "SHIRTS-COMBO",
    material: "100% Cotton",
    type: "Y/D Waffle fabric Short Sleeve Shirts",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-8.png?updatedAt=1729851312860?tr:q-15",
    alt: "shirt-combo",
  },
  {
    category: "SHIRTS-COMBO",
    material: "100% Cotton",
    type: "Y/D Waffle Check Short Sleeve",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-7.png?updatedAt=1729851314783?tr:q-15",
    alt: "shirt-combo",
  },
  {
    category: "SHIRTS-COMBO",
    material: "100% Cotton",
    type: "Y/D Waffle Fabric Long Sleeve Shirts",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-6.png?updatedAt=1729851315453?tr:q-15",
    alt: "shirt-combo",
  },
  {
    category: "SHACKETS",
    material: "100% Cotton",
    type: "Heavy Weight Y/D Shackets",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-5.png?updatedAt=1729851317549?tr:q-15",
    alt: "Shackets",
  },
  {
    category: "SHORTS",
    material: "100% Cotton",
    type: "Cargo Shorts",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-4.png?updatedAt=1729851305294?tr:q-15",
    alt: "shorts",
  },
  {
    category: "SHORTS",
    material: "100% Cotton",
    type: "Cargo Shorts",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image.png?updatedAt=1729851315814?tr:q-15",
    alt: "shorts",
  },
  {
    category: "SHORTS",
    material: "100% Cotton",
    type: "Cargo Shorts",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-2.png?updatedAt=1729851275189?tr:q-15",
    alt: "shorts",
  },
  {
    category: "SHORTS",
    material: "100% Cotton",
    type: "Cargo Shorts",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-1.png?updatedAt=1729851269138?tr:q-15",
    alt: "shorts",
  },
  {
    category: "SHORTS",
    material: "100% Cotton",
    type: "Cargo Shorts",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-3.png?updatedAt=1729851285489?tr:q-15",
    alt: "shorts",
  },
];

export const women = [
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "5 Oz Twill Denim",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-20.png?updatedAt=1729851394596?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Zaves Chambray Shirt",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-21.png?updatedAt=1729851395513?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "3/4th Sleeve Top With Waist Tie Up",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-19.png?updatedAt=1729851385991?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Long Sleeve Denim Shirt",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-18.png?updatedAt=1729851384128?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Checked Shirt",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/WhatsApp%20Image%202024-10-20%20at%2015.12.25_a199baa0.png?updatedAt=1729851398445?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Long Sleeve Denim Shirt",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-17.png?updatedAt=1729851383990?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Modal",
    type: "Long Sleeves",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-16.png?updatedAt=1729851382365?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "60% Cotton, 40% Viscose",
    type: "Long Sleeves",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-15.png?updatedAt=1729851383933?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Long Sleeves",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-14.png?updatedAt=1729851383340?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Double cloth Y/D Checks",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-13.png?updatedAt=1729851384684?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Organic Cotton - Crinkle",
    type: "Embroidery Top",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-12.png?updatedAt=1729851384151?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton",
    type: "Y/D Checks",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-11.png?updatedAt=1729851384852?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton Twill",
    type: "10.5 Oz",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/img-1.png?updatedAt=1738314417299?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton Twill,Denim",
    type: "5 Oz",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/img-2.png?updatedAt=1738314417370?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton Twill",
    type: "5 Oz",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/img-3.png?updatedAt=1738314417367?tr:q-15",
    alt: "shirt",
  },
  {
    category: "SHIRTS",
    material: "100% Cotton Twill,Denim",
    type: "5 Oz",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/img-4.png?updatedAt=1738314416285?tr:q-15",
    alt: "shirt",
  },
  {
    category: "DRESS",
    material: "100% Cotton",
    type: "5 Oz Twill Denim Chambray Puff Sleeve Dress",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-10.png?updatedAt=1729851382750?tr:q-15",
    alt: "Dress",
  },
  {
    category: "DRESS",
    material: "100% Cotton",
    type: "5 Oz Twill Denim Dress",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-9.png?updatedAt=1729851395848?tr:q-15",
    alt: "Dress",
  },
  {
    category: "DRESS",
    material: "100% Cotton",
    type: " 5 Oz Twill Denim",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-8.png?updatedAt=1729851396044?tr:q-15",
    alt: "Dress",
  },
  {
    category: "DRESS",
    material: "98% Cotton, 2% Spandex",
    type: "Denim Mini Dress",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-7.png?updatedAt=1729851395124?tr:q-15",
    alt: "Dress",
  },
  {
    category: "DRESS",
    material: "98.5% Cotton, 1.5% Elasthane",
    type: "10 Oz Stretch Denim Women Dress",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-6.png?updatedAt=1729851394020?tr:q-15",
    alt: "Dress",
  },
  {
    category: "DRESS",
    material: "100% Cotton",
    type: "Denim Long Dress",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-5.png?updatedAt=1729851395787?tr:q-15",
    alt: "Dress",
  },
  {
    category: "DRESS",
    material: "100% Cotton",
    type: "5 Oz Sleeveless Twill Denim Swirt Dress",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-3.png?updatedAt=1729851395892?tr:q-15",
    alt: "Dress",
  },
  {
    category: "DRESS",
    material: "100% Cotton",
    type: "5 Oz Twill Denim",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-4.png?updatedAt=1729851394578?tr:q-15",
    alt: "Dress",
  },
  {
    category: "DRESS",
    material: "100% Cotton",
    type: "Y/D Satin Women's Dress",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-2.png?updatedAt=1729851393030?tr:q-15",
    alt: "Dress",
  },
  {
    category: "DRESS",
    material: "100% Cotton Twill",
    type: "5 Oz",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/dress%20img-5.png?updatedAt=1738314416041?tr:q-15",
    alt: "Dress",
  },
  {
    category: "DRESS",
    material: "98% Cotton,2% Spandex Twill",
    type: "10 OZ",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/dress%20img-6.png?updatedAt=1738314417382?tr:q-15",
    alt: "Dress",
  },
  {
    category: "DRESS",
    material: "100% Cotton Twill",
    type: "5 Oz",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/dress%20img-7.png?updatedAt=1738314414400?tr:q-15",
    alt: "Dress",
  },
  {
    category: "DUNGAREE",
    material: "100% Cotton",
    type: "5 Oz Denim Dungaree",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-1.png?updatedAt=1729851384297?tr:q-15",
    alt: "Dungaree",
  },
  {
    category: "DUNGAREE",
    material: "100% Cotton blend",
    type: "6 Oz",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/dg%20img-8.png?updatedAt=1738314415786?tr:q-15",
    alt: "Dungaree",
  },
  {
    category: "DUNGAREE",
    material: "100% Cotton Twill,Denim",
    type: "5 Oz",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/dg%20img-9.png?updatedAt=1738314415688?tr:q-15",
    alt: "Dungaree",
  },
  {
    category: "SHORTS",
    material: "100% Cotton",
    type: "5 Oz Denim Chambray Shorts ",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image.png?updatedAt=1729851397049?tr:q-15",
    alt: "Shorts",
  },
];

export const kids = [
  {
    category: "BOYS SHIRTS",
    material: "100% Cotton",
    type: "3/4th Sleeve with Checks & Embroidery",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-20%20at%2015.15.43_c2f40b71.png?updatedAt=1729851454796?tr:q-15",
    alt: "Boys Shirt",
  },
  {
    category: "BOYS SHIRTS",
    material: "60% Recycled Cotton, 40% Polyester",
    type: "Y/D Twill Checks",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2012.02.59_e92e1993.png?updatedAt=1729851453332?tr:q-15",
    alt: "Boys Shirt",
  },
  {
    category: "BOYS SHIRTS",
    material: "100% Cotton",
    type: "YD checks",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image-17.png?updatedAt=1729851431883?tr:q-15",
    alt: "Boys Shirt",
  },
  {
    category: "BOYS SHIRTS",
    material: "100% Cotton",
    type: "Long Sleeve",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image-18.png?updatedAt=1729851425817?tr:q-15",
    alt: "Boys Shirt",
  },
  {
    category: "BOYS SHIRTS",
    material: "100% Cotton",
    type: "Dobby",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image-15.png?updatedAt=1729851429968?tr:q-15",
    alt: "Boys Shirt",
  },
  {
    category: "BOYS SHIRTS",
    material: "100% Cotton",
    type: "YD checks",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image-14.png?updatedAt=1729851433115?tr:q-15",
    alt: "Boys Shirt",
  },
  {
    category: "BOYS SHIRTS",
    material: "100% Cotton",
    type: "Y/D with Jersey",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image-13.png?updatedAt=1729851431075?tr:q-15",
    alt: "Boys Shirt",
  },
  {
    category: "GIRLS DRESS",
    material: "100% Viscose with AOP",
    type: "Long Sleeve Dress",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-18%20at%2018.20.54_af70f0c1.png?updatedAt=1729851442417?tr:q-15",
    alt: "Girls Dress",
  },
  {
    category: "GIRLS DRESS",
    material: " 100% Cotton",
    type: "AOP Double Cloth Dress",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2011.59.49_73d0b95b.png?updatedAt=1729851453171?tr:q-15",
    alt: "Girls Dress",
  },
  {
    category: "GIRLS DRESS",
    material: "50% Viscose, 50% Cotton",
    type: "Double cloth Solid Half Sleeve Dress",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2017.41.03_5fe77043.png?updatedAt=1729851453025?tr:q-15",
    alt: "Girls Dress",
  },
  {
    category: "GIRLS DRESS",
    material: "100% Cotton",
    type: "Y/D Twill Checks",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2012.05.49_08bcfec2.png?updatedAt=1729851453830?tr:q-15",
    alt: "Girls Dress",
  },
  {
    category: "GIRLS DRESS",
    material: "100% Cotton",
    type: "Seersucker Floral AOP Dress With Chest Smoking",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-20%20at%2016.14.02_eef54720.png?updatedAt=1729851456755?tr:q-15",
    alt: "Girls Dress",
  },
  {
    category: "GIRLS DRESS",
    material: "100% Tencil",
    type: "Girl’s Dress",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image-12.png?updatedAt=1729851423170?tr:q-15",
    alt: "Girls Dress",
  },
  {
    category: "GIRLS DRESS",
    material: "100% Rayon",
    type: "Girl’s Dress",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image-9.png?updatedAt=1729851444123?tr:q-15",
    alt: "Girls Dress",
  },
  {
    category: "GIRLS DRESS",
    material: "100% Viscose",
    type: "AOP",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image-10.png?updatedAt=1729851433396?tr:q-15",
    alt: "Girls Dress",
  },
  {
    category: "SKIRTS",
    material: "100% Viscose",
    type: "100% Organic Cotton",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2011.42.29_6d85cbba.png?updatedAt=1729851446156?tr:q-15",
    alt: "Skirts",
  },
  {
    category: "SKIRTS",
    material: "Double Panel Skirt",
    type: "Seer Sucker Y/D Checks",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-18%20at%2018.25.49_41604878.png?updatedAt=1729851443195?tr:q-15",
    alt: "Skirts",
  },
  {
    category: "SKIRTS",
    material: "100% Cotton",
    type: "Double Panel Skirt With Waist Smoking",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2012.09.25_7202f351.png?updatedAt=1729851453757?tr:q-15",
    alt: "Skirts",
  },
  {
    category: "SKIRTS",
    material: "100% Cotton",
    type: "Double Panel Skirt With Waist Smoking",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2010.19.28_f4a28c4a.png?updatedAt=1729851444565?tr:q-15",
    alt: "Skirts",
  },
  {
    category: "SKIRTS",
    material: "100% Organic Cotton",
    type: "Seer Sucker Y/D Checks",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-20%20at%2015.15.44_ee6094c9.png?updatedAt=1729851456074?tr:q-15",
    alt: "Skirts",
  },
  {
    category: "SKIRTS",
    material: "100% Cotton",
    type: "Dobby print",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image-8.png?updatedAt=1729851441262?tr:q-15",
    alt: "Skirts",
  },
  {
    category: "SKIRTS",
    material: "100% Viscose",
    type: "AOP",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image-6.png?updatedAt=1729851442521?tr:q-15",
    alt: "Skirts",
  },
  {
    category: "GIRLS BLOUSE",
    material: "50% Viscose, 50% Cotton",
    type: "Half Sleeve Blouse",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-18%20at%2018.22.18_666304d1.png?updatedAt=1729851441321?tr:q-15",
    alt: "Skirts",
  },
  {
    category: "GIRLS BLOUSE",
    material: "100% Viscose With AOP",
    type: "Printed 3/4th Sleeve Top",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2011.44.15_9c5152f6-1.png?updatedAt=1729851449901?tr:q-15",
    alt: "Skirts",
  },
  {
    category: "GIRLS BLOUSE",
    material: "100% Cotton",
    type: "Poplin with AOE",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image-5.png?updatedAt=1729851437545?tr:q-15",
    alt: "Skirts",
  },
  {
    category: "GIRLS BLOUSE",
    material: "100% Cotton",
    type: "Seer Sucker AOP",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image-4.png?updatedAt=1729851435412?tr:q-15",
    alt: "Skirts",
  },
  {
    category: "GIRLS SHORTS",
    material: "100% Cotton",
    type: "AOP Girls Shorts",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2012.08.06_50e56166.png?updatedAt=1729851454284?tr:q-15",
    alt: "Shorts",
  },
  {
    category: "GIRLS SHORTS",
    material: "Linen Cotton",
    type: "Wide Fit",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image-3.png?updatedAt=1729851433400?tr:q-15",
    alt: "Shorts",
  },
  {
    category: "GIRLS PANT",
    material: "100% Cotton",
    type: "10 Oz Twill Denim",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2011.21.41_9697a9c3.png?updatedAt=1729851446550?tr:q-15",
    alt: "Pants",
  },
  {
    category: "GIRLS  VEST",
    material: "100% Cotton",
    type: "Plain Weave with AOE",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image-2.png?updatedAt=1729851432864?tr:q-15",
    alt: "Vest",
  },
  {
    category: "GIRLS JACKET",
    material: "100% Cotton",
    type: "9 Ozs Denim",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image-1.png?updatedAt=1729851430301?tr:q-15",
    alt: "Jacket",
  },
  {
    category: "BOYS JACKET",
    material: "100% Cotton",
    type: "100%  Polyester Ripstop",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2012.05.04_84c4697b.png?updatedAt=1729851452043?tr:q-15",
    alt: "Jacket",
  },
  {
    category: "BOYS JACKET",
    material: "55% Viscose, 45% Cotton",
    type: "Weft Dobby",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image.png?updatedAt=1729851443029?tr:q-15",
    alt: "Jacket",
  },
];

export const infants = [
  {
    category: "BOYS SHIRTS",
    material: "97% Cotton, 3% Lycra",
    type: "3/4th Sleeve Solid Shirt",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image-15.png?updatedAt=1729851475261?tr:q-15",
    alt: "Shirts",
  },
  {
    category: "BOYS SHIRTS",
    material: "55% Viscose, 45% Cotton",
    type: "Shorts sleeve",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/WhatsApp%20Image%202024-10-18%20at%2018.22.55_a17a7337.png?updatedAt=1729851486413?tr:q-15",
    alt: "Shirts",
  },
  {
    category: "BOYS SHIRTS",
    material: "100% Organic Cotton ",
    type: "Twill Checks Full Sleeve Shirt",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/WhatsApp%20Image%202024-10-18%20at%2018.25.16_cb0c1e49.png?updatedAt=1729851487303?tr:q-15",
    alt: "Shirts",
  },
  {
    category: "BOYS SHIRTS",
    material: "100% Organic Cotton ",
    type: "Twill Checks Full Sleeve Shirt",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/WhatsApp%20Image%202024-10-18%20at%2018.25.16_70ebb16f.png?updatedAt=1729851486653?tr:q-15",
    alt: "Shirts",
  },
  {
    category: "BOYS SHIRTS",
    material: "100%  Cotton",
    type: "Y/D Checks",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image-14.png?updatedAt=1729851478750?tr:q-15",
    alt: "Shirts",
  },
  {
    category: "BOYS SHIRTS",
    material: "100%  Cotton",
    type: "Y/D Checks",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image-13.png?updatedAt=1729851477609?tr:q-15",
    alt: "Shirts",
  },
  // missing
  {
    category: "GIRLS SHIRTS",
    material: "100% Tencel",
    type: "Elbow Sleeve Girls Extended Shirt",
    img: "?tr:q-15",
    alt: "Shirts",
  },
  {
    category: "GIRLS TOPS",
    material: "100% Cotton",
    type: "Y/D Patch Work Weave",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/WhatsApp%20Image%202024-10-19%20at%2010.17.04_a9ee3910.png?updatedAt=1729851487795?tr:q-15",
    alt: "",
  },
  {
    category: "GIRLS TOPS",
    material: "98% Cotton, 2% Lurex",
    type: "3/4th Sleeve Girls Top",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/WhatsApp%20Image%202024-10-18%20at%2018.21.41_4de5ed7f.png?updatedAt=1729851484965?tr:q-15",
    alt: "Tops",
  },
  {
    category: "GIRLS TOPS",
    material: "100% Cotton",
    type: "Seer Sucker With Floral AOP",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/WhatsApp%20Image%202024-10-20%20at%2015.15.43_a94f3d4c.png?updatedAt=1729851491110?tr:q-15",
    alt: "Tops",
  },
  {
    category: "GIRLS TOPS",
    material: "100% Cotton",
    type: "Butta Dobby",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image-12.png?updatedAt=1729851477801?tr:q-15",
    alt: "Tops",
  },
  {
    category: "GIRLS TOPS",
    material: "100% Cotton",
    type: "Slub with AOP",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image-10.png?updatedAt=1729851477844?tr:q-15",
    alt: "Tops",
  },
  {
    category: "GIRLS TOPS",
    material: "100% Viscose",
    type: "AOP",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image-11.png?updatedAt=1729851478620?tr:q-15",
    alt: "Tops",
  },
  {
    category: "GIRLS TOPS",
    material: "100% Cotton",
    type: "Seer Sucker Y/D Check",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image-8.png?updatedAt=1729851485520?tr:q-15",
    alt: "Tops",
  },
  {
    category: "GIRLS TOPS",
    material: "100% Cotton",
    type: "Top",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image-9.png?updatedAt=1729851483860?tr:q-15",
    alt: "Tops",
  },
  {
    category: "GIRLS TOPS",
    material: "100% Viscose",
    type: "Solid",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image-6.png?updatedAt=1729851481079?tr:q-15",
    alt: "Tops",
  },
  {
    category: "GIRLS TOPS",
    material: "100% Cotton",
    type: "Dobby",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image-7.png?updatedAt=1729851484659?tr:q-15",
    alt: "Tops",
  },
  {
    category: "GIRLS DRESS",
    material: "100% Cotton",
    type: "Seer Sucker Infants Dress",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/WhatsApp%20Image%202024-10-19%20at%2011.41.50_c963a401.png?updatedAt=1729851490825?tr:q-15",
    alt: "Dress",
  },
  {
    category: "GIRLS DRESS",
    material: "100% Cotton",
    type: "Slub with AOP",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image-5.png?updatedAt=1729851480368?tr:q-15",
    alt: "Dress",
  },
  {
    category: "GIRLS DRESS",
    material: "100% Cotton",
    type: "Y/D Checks",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image-3.png?updatedAt=1729851479155?tr:q-15",
    alt: "Dress",
  },
  {
    category: "GIRLS DRESS",
    material: "100% Cotton",
    type: "Long Sleeves",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image-4.png?updatedAt=1729851480164?tr:q-15",
    alt: "Dress",
  },
  {
    category: "JUMPSUIT",
    material: "100% Cotton",
    type: "Girl’s Jumpsuit 5 Oz Twill Denim Chambray Puff Sleeve Dress",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/WhatsApp%20Image%202024-10-18%20at%2018.23.18_9f5f5565.png?updatedAt=1729851486206?tr:q-15",
    alt: "Jumpsuit",
  },
  {
    category: "JUMPSUIT",
    material: "97% Cotton, 3% Lycra ",
    type: "Twill Lycra",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image-16.png?updatedAt=1729851475961?tr:q-15",
    alt: "Jumpsuit",
  },
  {
    category: "GIRLS PANT",
    material: "100% Viscose",
    type: "AOP Full Length Pants With Waist Tie-up",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/WhatsApp%20Image%202024-10-19%20at%2017.07.43_72eef9c2.png?updatedAt=1729851490588?tr:q-15",
    alt: "Pants",
  },
  {
    category: "GIRLS SHORTS",
    material: "100% Cotton",
    type: "Slub with AOP",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image-1.png?updatedAt=1729851476627?tr:q-15",
    alt: "Shorts",
  },
  {
    category: "GIRLS SHORTS",
    material: "100% Cotton",
    type: "Dobby Print",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image-2.png?updatedAt=1729851478424?tr:q-15",
    alt: "Shorts",
  },
  {
    category: "BOYS SHORTS",
    material: "100% Organic Cotton",
    type: "Baby boy Shorts",
    img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image.png?updatedAt=1729851484875?tr:q-15",
    alt: "Shorts",
  },
];
