export const navbarLinks = [
    { menu: "About Us", ref: "/about", path: "about" },
    { menu: "Services", ref: "/services", path: "services" },
    { menu: "Products", ref: "/products", path: "products" },
    { menu: "Certifications", ref: "/certifications", path: "certifications" },
    { menu: "Gallery", ref: "/gallery", path: "gallery" },
    { menu: "Contact us", ref: "/contact", path: "contact" },
];

export const footerLinks = [
    { menu: "Home", ref: "/" },
    // { menu: "People of rasims", ref: "/initiatives#founder" },
    { menu: "T&C", ref: "/termsAndConditions" },
    { menu: "Policy", ref: "/policy" },
];

export const fabricTypes = [
    {
        title: "Men",
        desc: "Wool is not just a fiber, it’s a lifestyle.",
        ref: "/products#types",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/cards/mens-wear.png?updatedAt=1729668433466",
        link: "More",
    },
    {
        title: "Women",
        desc: "Denim is a love that never fades.",
        ref: "/products#types",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-4.png?updatedAt=1729851394578",
        link: "More",
    },
    {
        title: "Children",
        desc: "Cotton is the fabric of our lives.",
        ref: "/products#types",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image-10.png?updatedAt=1729851433396",
        link: "More",
    },
    {
        title: "Infants",
        desc: "Cotton is the fabric of our lives.",
        ref: "/products#types",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/WhatsApp%20Image%202024-10-18%20at%2018.25.16_70ebb16f.png?updatedAt=1729851486653",
        link: "More",
    },
];

export const certification = [
    {
        title: "sedex",
        desc: "",
        ref: "/certifications#certificate",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/certification%20logo/sedex-logo.webp?updatedAt=1729674199654",
        link: "More",
    },
    {
        title: "ECCC",
        desc: "",
        ref: "/certifications#certificate",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/certification%20logo/sa8000-logo.webp?updatedAt=1729675027551",
        link: "More",
    },
    {
        title: "GOTS",
        desc: "",
        ref: "/certifications#certificate",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/certification%20logo/gots-logo.jpg?updatedAt=1729675198071",
        link: "More",
    },
    {
        title: "Accordia",
        desc: "",
        ref: "/certifications#certificate",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/certification_page/logos/logo%203.png?updatedAt=1728093506587",
        link: "More",
    },
    {
        title: "Oek Tex",
        desc: "",
        ref: "/certifications#certificate",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/certification%20logo/tex-logo.png?updatedAt=1729842583325",
        link: "More",
    },
    {
        title: "Wrap",
        desc: "",
        ref: "/certifications#certificate",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/certification%20logo/wrap-logo.png?updatedAt=1729842584266",
        link: "More",
    },
    {
        title: "organic blend",
        desc: "",
        ref: "/certifications#certificate",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/certification_page/logos/logo%207.png?updatedAt=1728093507060",
        link: "More",
    },
];

export const variousProducts = [
    {
        title: "Men",
        ref: "/products#types",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/grid%201.png?updatedAt=1729863471989",
        lists: ["Shirts", "Shorts"],
    },
    {
        title: "Women",
        ref: "/products#types",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/grid%202.png?updatedAt=1729863471993",
        lists: ["Shirts", "Skirts"],
    },
    {
        title: "Children",
        ref: "/products#types",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/grid%203.png?updatedAt=1729863471834",
        lists: ["Top", "bottom"],
    },
    {
        title: "Infants",
        ref: "/products#types",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/grid%204.png?updatedAt=1729863471800",
        lists: ["Shirts", "Shorts"],
    },
];

export const carouselImg = [
    {
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/gallery_page/gallery1.jpg?updatedAt=1729846570403",
        style: "object-center",
    },
    {
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/gallery_page/gallery2.jpg?updatedAt=1729846570038",
        style: "object-center",
    },
    {
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/gallery_page/gallery3.jpg?updatedAt=1729846547773",
        style: "object-center",
    },
    {
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/gallery_page/gallery4.jpg?updatedAt=1729846545957",
        style: "object-top",
    },
    {
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/gallery_page/gallery6.jpg?updatedAt=1729846554555",
        style: "object-center",
    },
    {
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/gallery_page/gallery7.jpg?updatedAt=1729846555365",
        style: "object-center",
    },
    {
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/gallery_page/gallery8.jpg?updatedAt=1729846548361",
        style: "object-center",
    },
    {
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/gallery_page/gallery9.jpg?updatedAt=1729846556710",
        style: "object-center",
    },
    {
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/gallery_page/gallery10.jpg?updatedAt=1729846543499",
        style: "object-bottom",
    },
];

export const logos = [
    {
        alt: "Hinano Life",
        src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimbuyers/Ellipse%205.svg",
    },
    {
        alt: "Petrol",
        src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimbuyers/Ellipse%204.svg",
    },
    {
        alt: "Pan Handle",
        src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimbuyers/Ellipse%208.svg",
    },
    {
        alt: "OldTejas",
        src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimbuyers/lo5.svg",
    },
    {
        alt: "Ellus",
        src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimbuyers/c2.svg",
    },
    {
        alt: "ariat",
        src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimbuyers/Ellipse%202.svg",
    },
    {
        alt: "Silent Theory",
        src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimbuyers/c4.svg",
    },
    {
        alt: "Little Dutch",
        src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimbuyers/Ellipse%203.svg",
    },
    {
        alt: "Rock&Roll",
        src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimbuyers/Ellipse%201.svg",
    },
    {
        alt: "French Connection",
        src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimbuyers/Ellipse%206.svg",
    },
    {
        alt: "Molo",
        src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimbuyers/Ellipse%207.svg",
    },
    {
        alt: "Mormaii",
        src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimbuyers/c3.svg",
    },
];

export const fabricCollections = [
    
    {   category: "Fabric",
        alt: "fabric name",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/product_page/Fabric%20collections/fabric%201.jpeg?updatedAt=1728093008059",
        type: "100% Cotton Yarn dyed Jacquard",
        material: "",
       
    },
    {
        alt: "fabric name",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/product_page/Fabric%20collections/fabric%202.jpeg?updatedAt=1728092998646",
        type: "98% Cotton 2% Lurex Plain Weave",
        material: "",
    },
    {
        alt: "fabric name",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/product_page/Fabric%20collections/fabric%203.jpeg?updatedAt=1728093006684",
        type: "55% Cotton 45% Linen",
        material: "",
    },
    {
        alt: "fabric name",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/product_page/Fabric%20collections/fabric%204.jpeg?updatedAt=1728093008011",
        type: "98% Cotton 2% Lycra",
        material: "",
    },
    {
        alt: "fabric name",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/product_page/Fabric%20collections/fabric%205.jpeg?updatedAt=1728093004809",
        type: "10 Oz Denim 98% Cotton 2% Elasthane Twil Denim",
        material: "",
    },
    {
        alt: "fabric name",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/product_page/Fabric%20collections/fabric%206.jpeg?updatedAt=1728093006041",
        type: "5.5 Oz Twill Denim 100% Cotton",
        material: "",
    },
];

export const certificatePageLogos = [
    {
        alt: "Sodex",
        src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimcertificates/Rectangle%2028.svg",
    },
    {
        alt: "Wrap",
        src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimcertificates/Rectangle%2022.svg",
    },
    {
        alt: "Accordia",
        src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimcertificates/Rectangle%2027.svg",
    },
    {
        alt: "ECCC",
        src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimcertificates/Rectangle%2021.svg",
    },
    {
        alt: "GOTS",
        src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimcertificates/Rectangle%2020.svg",
    },
    {
        alt: "OEKO TEX",
        src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimcertificates/Rectangle%2029.svg",
    },
    {
        alt: "Organic Blended",
        src: "https://ik.imagekit.io/webibee/Rasim-Exports/logo/rasimcertificates/Rectangle%2024.svg",
    },
];

export const founderData = [
    {
        title: "Founder & Managing Director",
        desc: "R.VARUSAI MOHAMMED (B.E.)",
        ref: "/contact",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/founders/founder%201.jpeg?updatedAt=1729679727380",
        link: "Contact",
    },
    {
        title: "Director",
        desc: "V MOHAMED RASIM (B.E. , MFTech)",
        ref: "/contact",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/aboutUs_page/about%20page%20founder%202.jpeg?updatedAt=1728299397544",
        link: "Contact",
    },
];

export const founders = [
    {
        src: "https://ik.imagekit.io/webibee/Rasim-Exports/founders/founder%201.jpeg?updatedAt=1728273260885",
        name: "R.VARUSAI MOHAMMED (B.E.)",
        position: "Founder & Managing Director",
    },
    {
        src: "https://ik.imagekit.io/webibee/Rasim-Exports/aboutUs_page/about%20page%20founder%202.jpeg?updatedAt=1728299397544",
        name: "V MOHAMED RASIM (B.E. , MFTech)",
        position: "Director",
    },
    {
        src: "https://ik.imagekit.io/webibee/Rasim-Exports/founders/founder%203.jpeg?updatedAt=1728273259296",
        name: "Unknown Name",
        position: "Founder",
    },
    {
        src: "https://ik.imagekit.io/webibee/Rasim-Exports/founders/founder%204.jpeg?updatedAt=1728273260405",
        name: "Unknown Name",
        position: "Founder",
    },
    {
        src: "https://ik.imagekit.io/webibee/Rasim-Exports/founders/founder%205.jpeg?updatedAt=1728273258515",
        name: "Unknown Name",
        position: "Founder",
    },
    {
        src: "https://ik.imagekit.io/webibee/Rasim-Exports/founders/founder%206.jpeg?updatedAt=1728273260483",
        name: "Unknown Name",
        position: "Founder",
    },
    {
        src: "https://ik.imagekit.io/webibee/Rasim-Exports/founders/founder%207.jpeg?updatedAt=1728273258933",
        name: "Unknown Name",
        position: "Founder",
    },
    {
        src: "https://ik.imagekit.io/webibee/Rasim-Exports/founders/founder%208.jpeg?updatedAt=1728273259787",
        name: "Unknown Name",
        position: "Founder",
    },
];

export const REProcess = [
    {
        title: "Ethical Manufacturing",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/HomePage%20icons/RE-icon-1.svg",
        alt: "Manufacturing icon",
    },
    {
        title: "Quality Craftsmanship",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/HomePage%20icons/RE-icon-2.svg",
        alt: "Quality icon",
    },
    {
        title: "Buyer Centric approach",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/HomePage%20icons/RE-icon-3.svg",
        alt: "Buyer icon",
    },
    {
        title: "Global Standards",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/HomePage%20icons/RE-icon-4.svg",
        alt: "Global icon",
    },
    {
        title: "Efficient Port Access",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/HomePage%20icons/RE-icon-5.svg",
        alt: "Port icon",
    },
];

// dress collections

export const mens = [
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "Hawaiian Print Short Sleeves",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-21.png?updatedAt=1729851357043",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "Hawaiian Print Short Sleeves",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-20.png?updatedAt=1729851356579",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "Hawaiian Print Short Sleeves",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-19.png?updatedAt=1729851354220",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "Hawaiian Print Short Sleeves",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-18.png?updatedAt=1729851346898",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "Hawaiian Print Short Sleeves",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-17.png?updatedAt=1729851346716",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "Hawaiian Print Short Sleeves",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-16.png?updatedAt=1729851347025",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "Hawaiian Print Short Sleeves",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-13.png?updatedAt=1729851345741",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "Hawaiian Print Short Sleeves",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-12.png?updatedAt=1729851344787",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "Hawaiian Print Short Sleeves",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-15.png?updatedAt=1729851347100",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "Hawaiian Print Short Sleeves",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-14.png?updatedAt=1729851347065",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "Hawaiian Print Short Sleeves",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-11.png?updatedAt=1729851346699",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "Hawaiian Print Short Sleeves",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-10.png?updatedAt=1729851347102",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "Hawaiian Print Short Sleeves",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-9.png?updatedAt=1729851359982",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "Hawaiian Print Short Sleeves",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-8.png?updatedAt=1729851358755",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "Hawaiian Print Short Sleeves",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-7.png?updatedAt=1729851357970",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "Hawaiian Print Short Sleeves",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-6.png?updatedAt=1729851358474",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "Hawaiian Print Short Sleeves",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-4.png?updatedAt=1729851358675",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "Hawaiian Print Short Sleeves",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-5.png?updatedAt=1729851358033",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "Hawaiian Print Short Sleeves",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-2.png?updatedAt=1729851354293",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "Hawaiian Print Short Sleeves",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-3.png?updatedAt=1729851355916",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "Hawaiian Print Short Sleeves",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image.png?updatedAt=1729851360022",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "Hawaiian Print Short Sleeves",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/extra%20men's/image-1.png?updatedAt=1729851345277",
        alt: "shirt",
    },
    //men's
    {
        category: "SHIRTS",
        material: "59% Cotton, 41% Rayon",
        type: "2/60s + 2/40sf x 30s/68 x 64 Y/D HB Twill Check",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-37.png?updatedAt=1729851317284",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "16s x 16s / 84 x 60 Y/D Jacquard",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-36.png?updatedAt=1729851302382",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "2/20s x 2/20s / 52 x 44 Y/D Dobby",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-35.png?updatedAt=1729851301469",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "2 / 60s + 2 / 60s / 68 x 54 Y / D Jacquard",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-34.png?updatedAt=1729851301979",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "99% Cotton, 1% Spandex",
        type: "40s x 40s + 40 Lycra / 100 x 96",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-33.png?updatedAt=1729851302108",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "55% Cotton, 45% Polyester ",
        type: "45 PC x 45 PC / 110 x 70 Y/D Stripes",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-32.png?updatedAt=1729851292008",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "2/40s x 2/40s Y/D Grindle",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-31.png?updatedAt=1729851290416",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "20s + 2/40s x 20s + 2/40s Y/D Double Cloth",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-30.png?updatedAt=1729851292494",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Viscose",
        type: "40 v/s x 40 v/s",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-29.png?updatedAt=1729851292946",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Viscose",
        type: "40 v/s x 40 v/s",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-28.png?updatedAt=1729851292376",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Viscose",
        type: "30 s/f x 40 s/f Twill AOP",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-27.png?updatedAt=1729851290822 ",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "50s + 50s / 132x72 Twill AOP",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-26.png?updatedAt=1729851288250",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "18-Wales Y/D Corduroy Checks",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-25.png?updatedAt=1729851285478",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "18-Wales Y/D Corduroy Checks",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-24.png?updatedAt=1729851280003",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "63% Cotton, 34% Poly, 3% Spandex",
        type: "60s x 97D Lycra /  120 x 68 Camo AOP",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-23.png?updatedAt=1729851283486",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "63% Cotton, 34% Poly, 3% Spandex",
        type: "60s x 97D Lycra /  120 x 68 Camo AOP",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-22.png?updatedAt=1729851278592",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "63% Cotton, 34% Poly, 3% Spandex",
        type: "60s x 97D Lycra /  120 x 68 Camo AOP",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-20.png?updatedAt=1729851276258",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "Y/D Waffle Fabric Long Sleeve ",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-21.png?updatedAt=1729851277393",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "Twill - Solid",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-18.png?updatedAt=1729851272159",
        alt: "shirt",
    },
    {
        category: "SHIRTS-COMBO",
        material: "100% Viscose",
        type: "AOP",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-19.png?updatedAt=1729851275313",
        alt: "shirt-combo",
    },
    {
        category: "SHIRTS",
        material: "100% Linen",
        type: "Printed Shirt",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-16.png?updatedAt=1729851273198",
        alt: "shirt-combo",
    },
    {
        category: "SHIRTS",
        material: "100% Viscose",
        type: "Twill with AOP",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-17.png?updatedAt=1729851274093",
        alt: "shirt-combo",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "Twill with AOP",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-14.png?updatedAt=1729851274383",
        alt: "shirt-combo",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: " Twill Denim",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-15.png?updatedAt=1729851272555",
        alt: "shirt-combo",
    },
    {
        category: "SHIRTS-COMBO",
        material: "55% Cotton, 45% Linen",
        type: "Short Sleeve Shirts",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-13.png?updatedAt=1729851269449",
        alt: "shirt-combo",
    },
    {
        category: "SHIRTS-COMBO",
        material: "100% Viscose",
        type: "AOP Short Sleeve",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-12.png?updatedAt=1729851274020",
        alt: "shirt-combo",
    },
    {
        category: "SHIRTS-COMBO",
        material: "97% Cotton, 3% Spandex",
        type: "Long Sleeve Shirts",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-11.png?updatedAt=1729851271445",
        alt: "shirt-combo",
    },
    {
        category: "SHIRTS-COMBO",
        material: "100% Cotton",
        type: "Y/D Jacquard Long Sleeve Shirts",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-10.png?updatedAt=1729851273555",
        alt: "shirt-combo",
    },
    {
        category: "SHIRTS-COMBO",
        material: "100% Cotton",
        type: "Y/D Grindle Fabric Long Sleeve Shirts",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-9.png?updatedAt=1729851316452",
        alt: "shirt-combo",
    },
    {
        category: "SHIRTS-COMBO",
        material: "100% Cotton",
        type: "Y/D Waffle fabric Short Sleeve Shirts",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-8.png?updatedAt=1729851312860",
        alt: "shirt-combo",
    },
    {
        category: "SHIRTS-COMBO",
        material: "100% Cotton",
        type: "Y/D Waffle Check Short Sleeve",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-7.png?updatedAt=1729851314783",
        alt: "shirt-combo",
    },
    {
        category: "SHIRTS-COMBO",
        material: "100% Cotton",
        type: "Y/D Waffle Fabric Long Sleeve Shirts",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-6.png?updatedAt=1729851315453",
        alt: "shirt-combo",
    },
    {
        category: "SHACKETS",
        material: "100% Cotton",
        type: "Heavy Weight Y/D Shackets",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-5.png?updatedAt=1729851317549",
        alt: "Shackets",
    },
    {
        category: "SHORTS",
        material: "100% Cotton",
        type: "Cargo Shorts",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-4.png?updatedAt=1729851305294",
        alt: "shorts",
    },
    {
        category: "SHORTS",
        material: "100% Cotton",
        type: "Cargo Shorts",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image.png?updatedAt=1729851315814",
        alt: "shorts",
    },
    {
        category: "SHORTS",
        material: "100% Cotton",
        type: "Cargo Shorts",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-2.png?updatedAt=1729851275189",
        alt: "shorts",
    },
    {
        category: "SHORTS",
        material: "100% Cotton",
        type: "Cargo Shorts",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-1.png?updatedAt=1729851269138",
        alt: "shorts",
    },
    {
        category: "SHORTS",
        material: "100% Cotton",
        type: "Cargo Shorts",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/men/image-3.png?updatedAt=1729851285489",
        alt: "shorts",
    },
];

export const women = [
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "5 Oz Twill Denim",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-20.png?updatedAt=1729851394596",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "Zaves Chambray Shirt",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-21.png?updatedAt=1729851395513",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "3/4th Sleeve Top With Waist Tie Up",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-19.png?updatedAt=1729851385991",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "Long Sleeve Denim Shirt",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-18.png?updatedAt=1729851384128",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "Checked Shirt",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/WhatsApp%20Image%202024-10-20%20at%2015.12.25_a199baa0.png?updatedAt=1729851398445",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "Long Sleeve Denim Shirt",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-17.png?updatedAt=1729851383990",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Modal",
        type: "Long Sleeves",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-16.png?updatedAt=1729851382365",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "60% Cotton, 40% Viscose",
        type: "Long Sleeves",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-15.png?updatedAt=1729851383933",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "Long Sleeves",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-14.png?updatedAt=1729851383340",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "Double cloth Y/D Checks",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-13.png?updatedAt=1729851384684",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Organic Cotton - Crinkle",
        type: "Embroidery Top",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-12.png?updatedAt=1729851384151",
        alt: "shirt",
    },
    {
        category: "SHIRTS",
        material: "100% Cotton",
        type: "Y/D Checks",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-11.png?updatedAt=1729851384852",
        alt: "shirt",
    },
    {
        category: "DRESS",
        material: "100% Cotton",
        type: "5 Oz Twill Denim Chambray Puff Sleeve Dress",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-10.png?updatedAt=1729851382750",
        alt: "Dress",
    },
    {
        category: "DRESS",
        material: "100% Cotton",
        type: "5 Oz Twill Denim Dress",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-9.png?updatedAt=1729851395848",
        alt: "Dress",
    },
    {
        category: "DRESS",
        material: "100% Cotton",
        type: " 5 Oz Twill Denim",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-8.png?updatedAt=1729851396044",
        alt: "Dress",
    },
    {
        category: "DRESS",
        material: "98% Cotton, 2% Spandex",
        type: "Denim Mini Dress",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-7.png?updatedAt=1729851395124",
        alt: "Dress",
    },
    {
        category: "DRESS",
        material: "98.5% Cotton, 1.5% Elasthane",
        type: "10 Oz Stretch Denim Women Dress",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-6.png?updatedAt=1729851394020",
        alt: "Dress",
    },
    {
        category: "DRESS",
        material: "00% Cotton",
        type: "Denim Long Dress",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-5.png?updatedAt=1729851395787",
        alt: "Dress",
    },
    {
        category: "DRESS",
        material: "100% Cotton",
        type: "5 Oz Sleeveless Twill Denim Swirt Dress",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-3.png?updatedAt=1729851395892",
        alt: "Dress",
    },
    {
        category: "DRESS",
        material: "100% Cotton",
        type: "5 Oz Twill Denim",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-4.png?updatedAt=1729851394578",
        alt: "Dress",
    },
    {
        category: "DRESS",
        material: "100% Cotton",
        type: "Y/D Satin Women's Dress",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-2.png?updatedAt=1729851393030",
        alt: "Dress",
    },
    {
        category: "DUNGAREE",
        material: "100% Cotton",
        type: "5 Oz Denim Dungaree",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image-1.png?updatedAt=1729851384297",
        alt: "Dungaree",
    },
    {
        category: "SHORTS",
        material: "100% Cotton",
        type: "5 Oz Denim Chambray Shorts ",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/women/image.png?updatedAt=1729851397049",
        alt: "Shorts",
    },
];

export const kids = [
    {
        category: "BOYS SHIRTS",
        material: "100% Cotton",
        type: "3/4th Sleeve with Checks & Embroidery",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-20%20at%2015.15.43_c2f40b71.png?updatedAt=1729851454796",
        alt: "Boys Shirt",
    },
    {
        category: "BOYS SHIRTS",
        material: "60% Recycled Cotton, 40% Polyester",
        type: "Y/D Twill Checks",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2012.02.59_e92e1993.png?updatedAt=1729851453332",
        alt: "Boys Shirt",
    },
    {
        category: "BOYS SHIRTS",
        material: "100% Cotton",
        type: "YD checks",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image-17.png?updatedAt=1729851431883",
        alt: "Boys Shirt",
    },
    {
        category: "BOYS SHIRTS",
        material: "100% Cotton",
        type: "Long Sleeve",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image-18.png?updatedAt=1729851425817",
        alt: "Boys Shirt",
    },
    {
        category: "BOYS SHIRTS",
        material: "100% Cotton",
        type: "Dobby",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image-15.png?updatedAt=1729851429968",
        alt: "Boys Shirt",
    },
    {
        category: "BOYS SHIRTS",
        material: "100% Cotton",
        type: "YD checks",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image-14.png?updatedAt=1729851433115",
        alt: "Boys Shirt",
    },
    {
        category: "BOYS SHIRTS",
        material: "100% Cotton",
        type: "Y/D with Jersey",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image-13.png?updatedAt=1729851431075",
        alt: "Boys Shirt",
    },
    {
        category: "GIRLS DRESS",
        material: "100% Viscose with AOP",
        type: "Long Sleeve Dress",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-18%20at%2018.20.54_af70f0c1.png?updatedAt=1729851442417",
        alt: "Girls Dress",
    },
    {
        category: "GIRLS DRESS",
        material: " 100% Cotton",
        type: "AOP Double Cloth Dress",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2011.59.49_73d0b95b.png?updatedAt=1729851453171",
        alt: "Girls Dress",
    },
    {
        category: "GIRLS DRESS",
        material: "50% Viscose, 50% Cotton",
        type: "Double cloth Solid Half Sleeve Dress",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2017.41.03_5fe77043.png?updatedAt=1729851453025",
        alt: "Girls Dress",
    },
    {
        category: "GIRLS DRESS",
        material: "100% Cotton",
        type: "Y/D Twill Checks",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2012.05.49_08bcfec2.png?updatedAt=1729851453830",
        alt: "Girls Dress",
    },
    {
        category: "GIRLS DRESS",
        material: "100% Cotton",
        type: "Seersucker Floral AOP Dress With Chest Smoking",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-20%20at%2016.14.02_eef54720.png?updatedAt=1729851456755",
        alt: "Girls Dress",
    },
    {
        category: "GIRLS DRESS",
        material: "100% Tencil",
        type: "Girl’s Dress",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image-12.png?updatedAt=1729851423170",
        alt: "Girls Dress",
    },
    {
        category: "GIRLS DRESS",
        material: "100% Rayon",
        type: "Girl’s Dress",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image-9.png?updatedAt=1729851444123",
        alt: "Girls Dress",
    },
    {
        category: "GIRLS DRESS",
        material: "100% Viscose",
        type: "AOP",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image-10.png?updatedAt=1729851433396",
        alt: "Girls Dress",
    },
    {
        category: "SKIRTS",
        material: "100% Viscose",
        type: "100% Organic Cotton",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2011.42.29_6d85cbba.png?updatedAt=1729851446156",
        alt: "Skirts",
    },
    {
        category: "SKIRTS",
        material: "Double Panel Skirt",
        type: "Seer Sucker Y/D Checks",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-18%20at%2018.25.49_41604878.png?updatedAt=1729851443195",
        alt: "Skirts",
    },
    {
        category: "SKIRTS",
        material: "100% Cotton",
        type: "Double Panel Skirt With Waist Smoking",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2012.09.25_7202f351.png?updatedAt=1729851453757",
        alt: "Skirts",
    },
    {
        category: "SKIRTS",
        material: "100% Cotton",
        type: "Double Panel Skirt With Waist Smoking",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2010.19.28_f4a28c4a.png?updatedAt=1729851444565",
        alt: "Skirts",
    },
    {
        category: "SKIRTS",
        material: "100% Organic Cotton",
        type: "Seer Sucker Y/D Checks",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-20%20at%2015.15.44_ee6094c9.png?updatedAt=1729851456074",
        alt: "Skirts",
    },
    {
        category: "SKIRTS",
        material: "100% Cotton",
        type: "Dobby print",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image-8.png?updatedAt=1729851441262",
        alt: "Skirts",
    },
    {
        category: "SKIRTS",
        material: "100% Viscose",
        type: "AOP",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image-6.png?updatedAt=1729851442521",
        alt: "Skirts",
    },
    {
        category: "GIRLS BLOUSE",
        material: "50% Viscose, 50% Cotton",
        type: "Half Sleeve Blouse",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-18%20at%2018.22.18_666304d1.png?updatedAt=1729851441321",
        alt: "Skirts",
    },
    {
        category: "GIRLS BLOUSE",
        material: "100% Viscose With AOP",
        type: "Printed 3/4th Sleeve Top",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2011.44.15_9c5152f6-1.png?updatedAt=1729851449901",
        alt: "Skirts",
    },
    {
        category: "GIRLS BLOUSE",
        material: "100% Cotton",
        type: "Poplin with AOE",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image-5.png?updatedAt=1729851437545",
        alt: "Skirts",
    },
    {
        category: "GIRLS BLOUSE",
        material: "100% Cotton",
        type: "Seer Sucker AOP",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image-4.png?updatedAt=1729851435412",
        alt: "Skirts",
    },
    {
        category: "GIRLS SHORTS",
        material: "100% Cotton",
        type: "AOP Girls Shorts",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2012.08.06_50e56166.png?updatedAt=1729851454284",
        alt: "Shorts",
    },
    {
        category: "GIRLS SHORTS",
        material: "Linen Cotton",
        type: "Wide Fit",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image-3.png?updatedAt=1729851433400",
        alt: "Shorts",
    },
    {
        category: "GIRLS PANT",
        material: "100% Cotton",
        type: "10 Oz Twill Denim",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2011.21.41_9697a9c3.png?updatedAt=1729851446550",
        alt: "Pants",
    },
    {
        category: "GIRLS  VEST",
        material: "100% Cotton",
        type: "Plain Weave with AOE",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image-2.png?updatedAt=1729851432864",
        alt: "Vest",
    },
    {
        category: "GIRLS JACKET",
        material: "100% Cotton",
        type: "9 Ozs Denim",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image-1.png?updatedAt=1729851430301",
        alt: "Jacket",
    },
    {
        category: "BOYS JACKET",
        material: "100% Cotton",
        type: "100%  Polyester Ripstop",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/WhatsApp%20Image%202024-10-19%20at%2012.05.04_84c4697b.png?updatedAt=1729851452043",
        alt: "Jacket",
    },
    {
        category: "BOYS JACKET",
        material: "55% Viscose, 45% Cotton",
        type: "Weft Dobby",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/kids/image.png?updatedAt=1729851443029",
        alt: "Jacket",
    },
];

export const infants = [
    {
        category: "BOYS SHIRTS",
        material: "97% Cotton, 3% Lycra",
        type: "3/4th Sleeve Solid Shirt",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image-15.png?updatedAt=1729851475261",
        alt: "Shirts",
    },
    {
        category: "BOYS SHIRTS",
        material: "55% Viscose, 45% Cotton",
        type: "Shorts sleeve",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/WhatsApp%20Image%202024-10-18%20at%2018.22.55_a17a7337.png?updatedAt=1729851486413",
        alt: "Shirts",
    },
    {
        category: "BOYS SHIRTS",
        material: "100% Organic Cotton ",
        type: "Twill Checks Full Sleeve Shirt",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/WhatsApp%20Image%202024-10-18%20at%2018.25.16_cb0c1e49.png?updatedAt=1729851487303",
        alt: "Shirts",
    },
    {
        category: "BOYS SHIRTS",
        material: "100% Organic Cotton ",
        type: "Twill Checks Full Sleeve Shirt",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/WhatsApp%20Image%202024-10-18%20at%2018.25.16_70ebb16f.png?updatedAt=1729851486653",
        alt: "Shirts",
    },
    {
        category: "BOYS SHIRTS",
        material: "100%  Cotton",
        type: "Y/D Checks",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image-14.png?updatedAt=1729851478750",
        alt: "Shirts",
    },
    {
        category: "BOYS SHIRTS",
        material: "100%  Cotton",
        type: "Y/D Checks",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image-13.png?updatedAt=1729851477609",
        alt: "Shirts",
    },
    // missing
    {
        category: "GIRLS SHIRTS",
        material: "100% Tencel",
        type: "Elbow Sleeve Girls Extended Shirt",
        img: "",
        alt: "Shirts",
    },
    {
        category: "GIRLS TOPS",
        material: "100% Cotton",
        type: "Y/D Patch Work Weave",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/WhatsApp%20Image%202024-10-19%20at%2010.17.04_a9ee3910.png?updatedAt=1729851487795",
        alt: "",
    },
    {
        category: "GIRLS TOPS",
        material: "98% Cotton, 2% Lurex",
        type: "3/4th Sleeve Girls Top",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/WhatsApp%20Image%202024-10-18%20at%2018.21.41_4de5ed7f.png?updatedAt=1729851484965",
        alt: "Tops",
    },
    {
        category: "GIRLS TOPS",
        material: "100% Cotton",
        type: "Seer Sucker With Floral AOP",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/WhatsApp%20Image%202024-10-20%20at%2015.15.43_a94f3d4c.png?updatedAt=1729851491110",
        alt: "Tops",
    },
    {
        category: "GIRLS TOPS",
        material: "100% Cotton",
        type: "Butta Dobby",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image-12.png?updatedAt=1729851477801",
        alt: "Tops",
    },
    {
        category: "GIRLS TOPS",
        material: "100% Cotton",
        type: "Slub with AOP",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image-10.png?updatedAt=1729851477844",
        alt: "Tops",
    },
    {
        category: "GIRLS TOPS",
        material: "100% Viscose",
        type: "AOP",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image-11.png?updatedAt=1729851478620",
        alt: "Tops",
    },
    {
        category: "GIRLS TOPS",
        material: "100% Cotton",
        type: "Seer Sucker Y/D Check",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image-8.png?updatedAt=1729851485520",
        alt: "Tops",
    },
    {
        category: "GIRLS TOPS",
        material: "100% Cotton",
        type: "Top",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image-9.png?updatedAt=1729851483860",
        alt: "Tops",
    },
    {
        category: "GIRLS TOPS",
        material: "100% Viscose",
        type: "Solid",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image-6.png?updatedAt=1729851481079",
        alt: "Tops",
    },
    {
        category: "GIRLS TOPS",
        material: "100% Cotton",
        type: "Dobby",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image-7.png?updatedAt=1729851484659",
        alt: "Tops",
    },
    {
        category: "GIRLS DRESS",
        material: "100% Cotton",
        type: "Seer Sucker Infants Dress",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/WhatsApp%20Image%202024-10-19%20at%2011.41.50_c963a401.png?updatedAt=1729851490825",
        alt: "Dress",
    },
    {
        category: "GIRLS DRESS",
        material: "100% Cotton",
        type: "Slub with AOP",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image-5.png?updatedAt=1729851480368",
        alt: "Dress",
    },
    {
        category: "GIRLS DRESS",
        material: "100% Cotton",
        type: "Y/D Checks",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image-3.png?updatedAt=1729851479155",
        alt: "Dress",
    },
    {
        category: "GIRLS DRESS",
        material: "100% Cotton",
        type: "Long Sleeves",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image-4.png?updatedAt=1729851480164",
        alt: "Dress",
    },
    {
        category: "JUMPSUIT",
        material: "100% Cotton",
        type: "Girl’s Jumpsuit 5 Oz Twill Denim Chambray Puff Sleeve Dress",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/WhatsApp%20Image%202024-10-18%20at%2018.23.18_9f5f5565.png?updatedAt=1729851486206",
        alt: "Jumpsuit",
    },
    {
        category: "JUMPSUIT",
        material: "97% Cotton, 3% Lycra ",
        type: "Twill Lycra",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image-16.png?updatedAt=1729851475961",
        alt: "Jumpsuit",
    },
    {
        category: "GIRLS PANT",
        material: "100% Viscose",
        type: "AOP Full Length Pants With Waist Tie-up",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/WhatsApp%20Image%202024-10-19%20at%2017.07.43_72eef9c2.png?updatedAt=1729851490588",
        alt: "Pants",
    },
    {
        category: "GIRLS SHORTS",
        material: "100% Cotton",
        type: "Slub with AOP",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image-1.png?updatedAt=1729851476627",
        alt: "Shorts",
    },
    {
        category: "GIRLS SHORTS",
        material: "100% Cotton",
        type: "Dobby Print",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image-2.png?updatedAt=1729851478424",
        alt: "Shorts",
    },
    {
        category: "BOYS SHORTS",
        material: "100% Organic Cotton",
        type: "Baby boy Shorts",
        img: "https://ik.imagekit.io/webibee/Rasim-Exports/dress%20collections/infants/image.png?updatedAt=1729851484875",
        alt: "Shorts",
    },
];
